// Fold src/assets/freeport/*.glb and *.webp into one generated module, src/assets/freeport/data.js.
//
//   node tools/freeport-import/pack.mjs
//
// The single-file build (tools/bundle.mjs) allows neither fetch() nor data: URIs, so, exactly like the
// Dungeon Crawlers library before it (src/assets/propsModel.js), the bytes ship inside the JS bundle as
// base64 and are decoded on first use. No gzip: the textures are already WebP, and a synchronous parse of
// the geometry (render/props/freeport.js) is what lets a room build its chests in the same frame.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const DIR = path.join(REPO, 'src/assets/freeport');
const files = fs.readdirSync(DIR).filter((f) => /\.(glb|webp)$/.test(f)).sort();
let js = '// GENERATED by tools/freeport-import/pack.mjs from the .glb and .webp files beside it. Do not edit.\n';
js += '// See README.md in this folder for the sources and the settings.\n';
js += '/** file name -> base64 bytes */\nexport const FREEPORT_FILES = {\n';
let total = 0;
for (const f of files) {
  const b = fs.readFileSync(path.join(DIR, f));
  total += b.length;
  js += `  '${f}': '${b.toString('base64')}',\n`;
  console.log(`${f.padEnd(24)} ${(b.length / 1024).toFixed(1).padStart(7)} KB`);
}
js += '};\n';
fs.writeFileSync(path.join(DIR, 'data.js'), js);
console.log(`${files.length} files, ${(total / 1024).toFixed(1)} KB raw -> data.js ${(js.length / 1024).toFixed(1)} KB`);
