// humans: the SIX trained fighters of the human family, drawn as HD-2D pixel sprites in the one
// house style (sprites/style.js) — dwarven guard, mercenary, swordsman, monk, dark warrior and the
// War Lord. Every one of them is a real MONSTER_TABLE type; nothing fictional is drawn here.
//
// These six used to be low-poly meshes standing in a room full of hand-pixelled sprites. The whole
// job of this file is that a player, at gameplay distance, with no name plate and no health bar,
// can tell them apart from each other AND from the humanoid.js warriors (rogue, barbarian, elvin
// ranger, assassin) by SILHOUETTE alone:
//
//   dwarven guard  the widest-for-its-height thing in the game: a brimmed helm bigger than the
//                  face under it, a forked beard down to the belt, a mail skirt to the ankles, and
//                  a single-bit BEARDED AXE whose crescent is half his own height. Squat.
//   mercenary      the plain one, on purpose: cropped hair under a sweatband, a buff-leather
//                  jerkin, ONE strapped pauldron, a plain arming sword down at his side and a
//                  small round buckler on the off hand. Working kit, nothing matching.
//   swordsman      the duellist: bolt upright, narrow, high collar and a sash, empty off hand held
//                  back for balance, and the LONGEST, slimmest blade in the group carried VERTICAL
//                  in front of the face — a straight line no other human silhouette contains.
//   monk           the only unarmoured, uncut outline: one hanging robe from shoulder to ankle, a
//                  shaved head, a rope belt, and a quarterstaff standing straight up past the top
//                  of the sprite. Calm; nothing on him points outward.
//   dark warrior   black plate with no skin anywhere: a closed sallet whose only feature is a
//                  narrow visor slit with a red ember burning behind it, spiked pauldrons, and a
//                  heavy dark longsword whose only bright note is the lit edge.
//   war lord       the boss. Drawn on a canvas half again as big as the rest, with a tall crimson
//                  plume over a gold-banded helm, pauldrons wider than his own stance, a crimson
//                  cape falling behind him to the floor, and a two-handed greatsword rising across
//                  his body. Nothing else in the human family is this tall or this wide.
//
// TWO CANVASES, ONE PIXEL DENSITY
//   MAN   48x48, pivot (24,45) — the five ordinary fighters, figures 34-43 px.
//   LORD  64x72, pivot (32,68) — the War Lord alone, figure 66 px.
// style.js SCALE says how tall each creature stands relative to the hero and `sizeFor` turns that
// into the billboard multiplier; drawing the War Lord at 66 px instead of squeezing him onto the
// 40-px canvas the other humans use is what keeps his texels the same size as everyone else's
// (1.18x) instead of double-size mush (2.11x). Every figure here lands in a 1.08-1.26 band.
//
// SHARED KEY VOCABULARY (identical to humanoid.js, so the two files read as one cast):
//   # outline (house INK)   @ lit edge      1 2 3 skin dark->light
//   7 4 5 6 cloth (7 = darkest crease)      8 9 0 leather      a b c d metal (+d specular)
//   e f g accent            T bone   E eye socket   W eye catch-light   Y glow (emissive)
//   G glint (emissive)      F hurt flash
// Ramps come from style.ramp(): shadows drift violet and gain saturation, highlights drift amber
// and lose a little. The key light is TOP-LEFT on every facing. Bodies are drawn WITHOUT their
// outline and inked by `ink()` afterwards, so the silhouette is exactly one pixel everywhere and
// softens to '@' on the edges that face the light.
//
// FACINGS south / east / north are each drawn; west is the mirrored east.
// CLIPS idle(4) walk(6) attack(4) hurt(2) death(5).
import {
  Palette, paint, compose, mirrorLit, outline, line, setPx, solid, makePix, smearArc, recolor,
} from '../pixelPainter.js';
import { INK, INK_LIT, LIT, ramp } from '../style.js';

// ------------------------------------------------------------------------------------ geometry
/** @typedef {{w:number,h:number,px:number,py:number,legX:number,legY:number,k:number}} Geom */

/** The ordinary-fighter canvas. `k` is the rig scale against humanoid.js's 40x40 rig. */
export const MAN = { w: 48, h: 48, px: 24, py: 45, legX: 16, legY: 33, k: 1 };
/** The War Lord's canvas: the same pixel density, more of it. */
export const LORD = { w: 64, h: 72, px: 32, py: 68, legX: 19, legY: 56, k: 1.65 };

/** Map a humanoid.js rig point (on its 40x40, pivot (20,37) canvas) onto a geometry. */
const rigPt = (G, x, y) => [Math.round(G.px + (x - 20) * G.k), Math.round(G.py + (y - 37) * G.k)];

// ------------------------------------------------------------------------------------ palette
// `ramp()` builds seven house steps; each vocabulary picks the ones it needs so a 3-key ramp is a
// slice of the same curve as a 4-key one and every species shares one contrast law.
// The house hue-shift is deliberately strong; over a SEVEN step ramp it will walk an olive all the
// way round to green, so the shift is dialled to the same figure the shipping cast uses (0.02) and
// each vocabulary takes the slice of the curve its material actually occupies: cloth and skin live
// in the middle (they are dyed and pigmented, not polished), metal reaches the top because a
// specular highlight is the whole point of steel, and leather sits between them.
const RAMP_OPTS = { hueShift: 0.02, satShift: 0.06 };
const RAMP_PICK = { skin: [1, 3, 5], cloth: [0, 2, 3, 4], leather: [1, 3, 4], metal: [1, 3, 5, 6], accent: [1, 3, 5] };

/**
 * One species palette over the shared key vocabulary. `picks` overrides which steps of the
 * seven-step house ramp a material takes — the Dark Warrior's plate is the same curve as the
 * Swordsman's, read from four steps lower down.
 * @param {{skin:string, cloth:string, leather:string, metal:string, accent:string, eye:string,
 *   tooth?:string, picks?:Object<string, number[]>}} o
 */
export function humanPalette(o) {
  const p = new Palette().set('#', INK).set('@', INK_LIT);
  const put = (keys, base, which) => {
    const r = ramp(base, 7, RAMP_OPTS);
    const pick = (o.picks && o.picks[which]) || RAMP_PICK[which];
    [...keys].forEach((k, i) => p.set(k, r[pick[i]]));
  };
  put('123', o.skin, 'skin');
  put('7456', o.cloth, 'cloth');   // 7 is the darkest crease, then 4 5 6 up to the lit fold
  put('890', o.leather, 'leather');
  put('abcd', o.metal, 'metal');   // d is a 1-px specular only
  put('efg', o.accent, 'accent');
  return p
    .set('T', o.tooth || '#ded2b8')
    .set('E', '#191322')
    .set('W', '#e6dcc8')
    .set('Y', o.eye)
    .set('G', '#efe9dd')
    .set('F', '#fff4f0');
}

// ------------------------------------------------------------------------------------ inking
const LIGHT_KEYS = new Set(['3', '6', '0', 'c', 'd', 'g', 'T', 'W'].map((c) => c.charCodeAt(0)));

/** Ink a hand-drawn body part: one-pixel house outline, softened to '@' on the lit edges. */
const ink = (p) => outline(p, '#', { lit: LIT, litKey: '@' });
/** Ink a block written as rows of keys (no outline characters in the source art). */
const body = (rows) => ink(paint(rows));

/** Soften a composed frame's remaining hard outline where a light tone meets empty space top-left. */
function softenLit(p) {
  const o = { w: p.w, h: p.h, d: new Uint16Array(p.d) };
  const HASH = 35, AT = 64;
  for (let y = 0; y < p.h; y++) for (let x = 0; x < p.w; x++) {
    if (p.d[y * p.w + x] !== HASH) continue;
    const inR = x + 1 < p.w ? p.d[y * p.w + x + 1] : 0, inD = y + 1 < p.h ? p.d[(y + 1) * p.w + x] : 0;
    const outL = x > 0 ? p.d[y * p.w + x - 1] : 0, outU = y > 0 ? p.d[(y - 1) * p.w + x] : 0;
    if ((LIGHT_KEYS.has(inR) && !outL) || (LIGHT_KEYS.has(inD) && !outU)) o.d[y * p.w + x] = AT;
  }
  return o;
}

// ------------------------------------------------------------------------------------ legs
// The house leg vocabulary, 16x12, stamped at (G.legX, G.legY): two 3-px legs with a 2-px gap and
// boots flaring outward, the screen-left leg carrying the lit tones. Copied key-for-key from
// humanoid.js so a mercenary and a rogue plant their feet the same way — one cast, one walk.
// Everything above the knee is covered by a hauberk, a robe or a skirt of plate on four of these
// six, so what actually shows is the boot; the poses still drive it.
const LEGS_S = {
  stand: paint(`
...#655#..#554#.
...#655#..#554#.
...#665#..#554#.
...#655#..#544#.
...#665#..#554#.
...#655#..#544#.
...#900#..#899#.
...#900#..#899#.
..#9000#..#8990#
..#9800#..#8890#
..#8890#..#8888#
..######..######`),
  lfwd: paint(`
...#655#..#554#.
...#655#..#554#.
...#665#..#554#.
...#655#..#544#.
...#665#..#554#.
...#655#.#899#..
...#900#.#899#..
...#900#.#8990#.
..#9000#.#8890#.
..#9800#.######.
..#8890#........
..######........`),
  rfwd: paint(`
...#655#..#554#.
...#655#..#554#.
...#665#..#554#.
...#655#..#544#.
...#665#..#554#.
....#900#.#554#.
....#900#.#899#.
...#9000#.#899#.
...#9800#.#8990#
...######.#8890#
..........#8888#
..........######`),
  pass: paint(`
...#655#..#554#.
...#655#..#554#.
...#665#..#554#.
...#655#..#544#.
...#665#..#554#.
...#655#..#544#.
...#900#..#899#.
...#900#..#899#.
..#9000#..#8990#
..#9800#..#8890#
..######..######
................`),
  squat: paint(`
................
................
................
..#655#..#554#..
.#655#....#554#.
.#900#....#899#.
#9000#....#8990#
#9800#....#8890#
#8890#....#8888#
######....######
................
................`),
  kneel: paint(`
................
................
................
..#655#.#554#...
..#655#.#554#...
..#900#.#899#...
.#9000#.#8990#..
.#9800#.#8890#..
.#88900#8888#...
.############...
................
................`),
  down: paint(`
................
................
................
................
................
..#655#..#554#..
..#900#..#899#..
.#9000#..#8990#.
.#98000##88990#.
.#888908888890#.
.#############..
................`),
};

const LEGS_E = {
  stand: paint(`
....#4#554#.....
....#4#554#.....
....#4#554#.....
....#4#554#.....
....#4#554#.....
....#4#554#.....
....#8#900#.....
....#8#900#.....
...#88#9000#....
...#88#9800#....
...#88#8890#....
...###.######...`),
  c1: paint(`
....#4#554#.....
....#4#554#.....
....#4#554#.....
....#4#.#54#....
....#4#..#554#..
....#4#..#554#..
....#8#..#900#..
....#8#..#900#..
...#88#..#9000#.
...#88#..#9800#.
...#88#..#8890#.
...###...######.`),
  p1: paint(`
....#4#554#.....
....#4#554#.....
....#4#554#.....
....#4#554#.....
....#4#554#.....
....#8#554#.....
....#8#900#.....
...#88#900#.....
...#88#9000#....
...####9800#....
......#8890#....
......######....`),
  c2: paint(`
....#4#554#.....
....#4#554#.....
....#4#554#.....
....#4#554#.....
...#4#.#554#....
..#4#..#554#....
..#8#..#900#....
.#8#...#900#....
.#88#..#9000#...
.#880#.#9800#...
.#889#.#8890#...
.#####.######...`),
  p2: paint(`
....#4#554#.....
....#4#554#.....
....#4#554#.....
....#4#554#.....
....#4#554#.....
....#8#554#.....
...#88#900#.....
...#88#900#.....
...####9000#....
......#9800#....
......#8890#....
......######....`),
};
LEGS_E.squat = LEGS_S.squat; LEGS_E.kneel = LEGS_S.kneel; LEGS_E.down = LEGS_S.down;

/** The same walk in plate: cloth and leather keys swapped for the metal ramp (dark warrior). */
const PLATE = { 4: 'a', 5: 'b', 6: 'c', 7: 'a', 8: 'a', 9: 'b', 0: 'c' };
const plated = (set) => Object.fromEntries(Object.entries(set).map(([k, p]) => [k, recolor(p, PLATE)]));
const LEGS_S_PLATE = plated(LEGS_S), LEGS_E_PLATE = plated(LEGS_E);

// The War Lord stands on a bigger floor: 26x12 greaves and sabatons under a skirt of plate, drawn
// at his own scale so his boots are as heavy as the rest of him.
const LORD_LEGS_S = {
  stand: paint(`
....#cbbb#....#bbba#.....
....#cbbb#....#bbba#.....
....#cbbb#....#bbba#.....
....#ccbb#....#bbaa#.....
...#ccbbb#..#bbbaaa#.....
...#cbbbb#..#bbbaaa#.....
..#ccbbbb#..#bbbaaaa#....
..#cbbbbb#..#bbaaaaa#....
.#ccbbbbb#..#bbaaaaaa#...
.#cbbbbbb#..#bbaaaaaa#...
.#bbbbbbb#..#bbaaaaaa#...
.##########..##########..`),
  lfwd: paint(`
....#cbbb#....#bbba#.....
....#cbbb#....#bbba#.....
....#cbbb#...#bbaa#......
....#ccbb#...#bbaa#......
...#ccbbb#..#bbaaa#......
...#cbbbb#..#bbaaa#......
..#ccbbbb#.#bbaaaa#......
..#cbbbbb#.#bbaaaa#......
.#ccbbbbb#.##########....
.#cbbbbbb#...............
.#bbbbbbb#...............
.##########..............`),
  pass: paint(`
....#cbbb#....#bbba#.....
....#cbbb#....#bbba#.....
....#cbbb#....#bbba#.....
....#ccbb#....#bbaa#.....
...#ccbbb#...#bbaaa#.....
...#cbbbb#...#bbaaa#.....
..#ccbbbb#..#bbaaaa#.....
..#cbbbbb#..#bbaaaa#.....
.#ccbbbbb#..#bbaaaaa#....
.#cbbbbbb#..#bbaaaaa#....
.##########..##########..
.........................`),
};
LORD_LEGS_S.rfwd = mirrorLit(LORD_LEGS_S.lfwd, 'ac');
const LORD_LEGS_E = {
  stand: paint(`
......#ba#.#cbbb#........
......#ba#.#cbbb#........
......#ba#.#cbbb#........
......#ba#.#ccbb#........
.....#bba#.#ccbbb#.......
.....#bba#.#cbbbb#.......
.....#bba#.#ccbbbb#......
.....#bba#.#cbbbbb#......
....#bbaa#.#ccbbbbb#.....
....#bbaa#.#cbbbbbb#.....
....#bbaa#.#bbbbbbb#.....
....######.##########....`),
  c1: paint(`
......#ba#.#cbbb#........
......#ba#.#cbbb#........
......#ba#..#cbbb#.......
......#ba#..#ccbb#.......
.....#bba#..#ccbbb#......
.....#bba#..#cbbbb#......
.....#bba#...#ccbbbb#....
.....#bba#...#cbbbbb#....
....#bbaa#...#ccbbbbb#...
....#bbaa#...#cbbbbbb#...
....#bbaa#...#bbbbbbb#...
....######...##########..`),
  p1: paint(`
......#ba#.#cbbb#........
......#ba#.#cbbb#........
......#ba#.#cbbb#........
.....#bba#.#ccbb#........
.....#bba#.#ccbbb#.......
.....#bba#.#cbbbb#.......
....#bbaa#.#ccbbbb#......
....#bbaa#.#cbbbbb#......
....######.#ccbbbbb#.....
...........#cbbbbbb#.....
...........#bbbbbbb#.....
...........##########....`),
};
LORD_LEGS_E.c2 = LORD_LEGS_E.c1; LORD_LEGS_E.p2 = LORD_LEGS_E.p1;
const LORD_COLLAPSE = {
  squat: paint(`
.........................
.........................
....#cbbb#....#bbba#.....
...#ccbbb#....#bbaaa#....
..#ccbbbb#....#bbaaaa#...
.#ccbbbbb#....#bbaaaaa#..
.#cbbbbbb#....#bbaaaaa#..
.#bbbbbbb#....#bbaaaaa#..
.##########....##########
.........................
.........................
.........................`),
  kneel: paint(`
.........................
.........................
.........................
...#cbbb#..#bbba#........
..#ccbbb#..#bbaaa#.......
.#ccbbbb#..#bbaaaa#......
.#cbbbbb#..#bbaaaaa#.....
.#bbbbbb#..#bbaaaaa#.....
.#bbbbbbbbbbbaaaaaa#.....
.####################....
.........................
.........................`),
  down: paint(`
.........................
.........................
.........................
.........................
...#cbbb#....#bbba#......
..#ccbbb#....#bbaaa#.....
.#ccbbbb#....#bbaaaa#....
.#cbbbbbbb##bbbaaaaa#....
.#bbbbbbbbbbbbbaaaaa#....
.#bbbbbbbbbbbbbbaaaa#....
.#####################...
.........................`),
};
Object.assign(LORD_LEGS_S, LORD_COLLAPSE);
Object.assign(LORD_LEGS_E, LORD_COLLAPSE);

// ------------------------------------------------------------------------------------ limbs
/**
 * A 2-px limb from shoulder (sx,sy) to hand (hx,hy), with a fist at the hand.
 * @param {Geom} G @param {{lit?:string, dark?:string, fist?:string, fistLit?:string, r?:number}} k
 */
function limbPix(G, sx, sy, hx, hy, k = {}) {
  const p = makePix(G.w, G.h);
  const lit = k.lit || '2', dark = k.dark || '1', fist = k.fist || '2', fistLit = k.fistLit || '3';
  line(p, sx, sy, hx, hy, lit);
  line(p, sx + 1, sy, hx + 1, hy, dark);
  if (G.k > 1.2) { line(p, sx - 1, sy, hx - 1, hy, lit); line(p, sx + 2, sy, hx + 2, hy, dark); }
  const r = k.r ?? (G.k > 1.2 ? 2 : 1);
  for (let y = -r; y <= r; y++) for (let x = -r; x <= r; x++) setPx(p, hx + x, hy + y, (x < 0 || y < 0) ? fistLit : fist);
  return ink(p);
}

// ------------------------------------------------------------------------------------ weapons
// Every weapon is marched along its own axis with a FILLED cross-section at each step: two
// Bresenham lines interleave into a checkerboard on diagonals, and a hollow section combs into a
// fork. `w0`/`w1` are the half-widths at the guard and at the tip, so the same code draws the
// swordsman's needle and the war lord's slab.
/**
 * A straight blade. `fuller` runs a shadow groove down the middle of a wide one, which is what
 * stops a greatsword reading as a plank.
 * @param {Geom} G
 */
function bladePix(G, gx, gy, angle, o = {}) {
  const { len = 12, w0 = 0.6, w1 = 0.6, glint = 0, grip = '9', pommel = 'e', guard = 0, fuller = false, dark = false } = o;
  const p = makePix(G.w, G.h);
  const a = (angle * Math.PI) / 180;
  const dx = Math.sin(a), dy = -Math.cos(a);
  const nx = -dy, ny = dx;
  const r = Math.round;
  const bx = gx + dx * 2.2, by = gy + dy * 2.2;
  const steps = Math.max(6, Math.round(len * 2.6));
  const edgeLit = dark ? 'c' : 'd', faceLit = dark ? 'b' : 'c', faceDark = dark ? 'a' : 'b';
  for (let i = 0; i <= steps; i++) {
    const t = i / steps;
    const cx = bx + dx * len * t, cy = by + dy * len * t;
    const hw = w0 + (w1 - w0) * t;
    for (let u = -hw; u <= hw; u += 0.3) {
      let key = u < -hw + 0.8 ? faceLit : u > hw - 0.8 ? 'a' : faceDark;
      if (fuller && Math.abs(u) < hw * 0.3) key = 'a';
      setPx(p, r(cx + nx * u), r(cy + ny * u), key);
    }
  }
  setPx(p, r(bx + dx * len), r(by + dy * len), edgeLit);
  setPx(p, r(bx + dx * len * 0.7 - nx * (w0 + (w1 - w0) * 0.7)), r(by + dy * len * 0.7 - ny * (w0 + (w1 - w0) * 0.7)), edgeLit);
  if (glint > 0) {
    const t = 0.34 + glint * 0.3;
    for (let k = 0; k < 2; k++) setPx(p, r(bx + dx * len * t + dx * k - nx * (w0 + (w1 - w0) * t)), r(by + dy * len * t + dy * k - ny * (w0 + (w1 - w0) * t)), 'G');
  }
  if (guard) for (let k = -guard; k <= guard; k++) setPx(p, r(bx - dx * 0.9 + nx * k), r(by - dy * 0.9 + ny * k), k <= -1 ? 'g' : k === 0 ? 'f' : 'e');
  const gripLen = Math.max(3, Math.round(2.6 * G.k));
  for (let k = 0; k < gripLen; k++) setPx(p, r(gx - dx * k), r(gy - dy * k), k === gripLen - 1 ? pommel : grip);
  return ink(p);
}

/**
 * A BEARDED AXE: one heavy crescent bit hanging off the near side of the haft, its cutting edge
 * bellying down well below the eye. A double-bit head is the barbarian's; this asymmetric hook is
 * the dwarf's, and the two never read as the same weapon.
 * @param {Geom} G
 */
function beardAxePix(G, gx, gy, angle, o = {}) {
  const { len = 16, head = 9, glint = 0, side = -1 } = o;
  const p = makePix(G.w, G.h);
  const a = (angle * Math.PI) / 180;
  const dx = Math.sin(a), dy = -Math.cos(a);
  const nx = -dy, ny = dx;
  const r = Math.round;
  const steps = Math.max(8, Math.round(len * 2.6));
  for (let i = 0; i <= steps; i++) {
    const t = i / steps;
    setPx(p, r(gx + dx * len * t), r(gy + dy * len * t), '9');
    setPx(p, r(gx + dx * len * t + nx * 0.9), r(gy + dy * len * t + ny * 0.9), '8');
  }
  setPx(p, r(gx - dx * 1.8), r(gy - dy * 1.8), 'e');
  setPx(p, r(gx - dx * 2.8), r(gy - dy * 2.8), 'f');
  // The bit is a true CRESCENT: an annulus centred inside the haft on the far side, so the cutting
  // edge bows out and the beard hooks back down toward the hands. Drawn by scanning the box the
  // crescent can occupy — an ellipse-minus-ellipse reads as an axe at 8 px where an outline blob
  // reads as a mitten.
  const ex = gx + dx * (len - 1.5), ey = gy + dy * (len - 1.5);
  const cx = ex - nx * head * 0.42 * side, cy = ey - ny * head * 0.42 * side;
  const rOut = head * 1.06, rIn = head * 0.46;
  for (let py = -Math.ceil(rOut) - 1; py <= Math.ceil(rOut) + 1; py++) {
    for (let px = -Math.ceil(rOut) - 1; px <= Math.ceil(rOut) + 1; px++) {
      const d = Math.hypot(px, py);
      if (d > rOut || d < rIn) continue;
      // keep only the half-disc that hangs off `side` of the haft, biased back toward the grip
      const along = (px * dx + py * dy) / (d || 1), across = ((px * nx + py * ny) / (d || 1)) * side;
      if (across < -0.12) continue;
      if (along > 0.72) continue;
      const t = (d - rIn) / (rOut - rIn);
      let key = t > 0.9 ? 'd' : t > 0.62 ? 'c' : t > 0.28 ? 'b' : 'a';
      if (along < -0.66) key = t > 0.7 ? 'b' : 'a';           // the beard, turned away from the light
      setPx(p, r(cx + px), r(cy + py), key);
    }
  }
  // the eye: the haft passes through the head
  for (let t = -1.2; t <= 1.8; t += 0.4) setPx(p, r(ex + dx * t), r(ey + dy * t), '9');
  if (glint > 0) setPx(p, r(cx + nx * rOut * 0.86 * side - dx * rOut * 0.3), r(cy + ny * rOut * 0.86 * side - dy * rOut * 0.3), 'G');
  return ink(p);
}

/**
 * A quarterstaff: a plain shaft with an iron ferrule at each end and a bound grip. The grip sits a
 * third of the way up, so the staff towers over the monk's head — the calm vertical that makes his
 * silhouette unmistakable.
 * @param {Geom} G
 */
function staffPix(G, gx, gy, angle, o = {}) {
  const { len = 26, glint = 0 } = o;
  const a = (angle * Math.PI) / 180;
  const dx = Math.sin(a), dy = -Math.cos(a);
  const nx = -dy, ny = dx;
  const p = makePix(G.w, G.h);
  const r = Math.round;
  const up = len * 0.66, down = len * 0.34;
  const steps = Math.round(len * 2.6);
  for (let i = 0; i <= steps; i++) {
    const t = -down + (up + down) * (i / steps);
    const cx = gx + dx * t, cy = gy + dy * t;
    const end = t > up - 2.2 || t < -down + 2.2;
    setPx(p, r(cx - nx * 0.5), r(cy - ny * 0.5), end ? 'c' : '0');
    setPx(p, r(cx + nx * 0.5), r(cy + ny * 0.5), end ? 'a' : '9');
  }
  for (let t = -2.2; t <= 2.2; t += 0.4) {            // the bound grip
    setPx(p, r(gx + dx * t - nx * 0.5), r(gy + dy * t - ny * 0.5), 'f');
    setPx(p, r(gx + dx * t + nx * 0.5), r(gy + dy * t + ny * 0.5), 'e');
  }
  if (glint > 0) setPx(p, r(gx + dx * (up - 1.4) - nx * 0.5), r(gy + dy * (up - 1.4) - ny * 0.5), 'G');
  return ink(p);
}

/** A small round buckler seen edge-on-ish: rim, boss and a lit crescent (the mercenary's off hand). */
function bucklerPix(G, cx, cy, rad = 5) {
  const p = makePix(G.w, G.h);
  const r = Math.round;
  for (let y = -rad; y <= rad; y++) for (let x = -rad * 0.72; x <= rad * 0.72; x += 0.5) {
    const d = Math.hypot(x / 0.72, y) / rad;
    if (d > 1) continue;
    let key = d > 0.86 ? '8' : d > 0.72 ? '9' : '0';
    if (x < 0 && y < 0 && d > 0.72) key = '0';
    if (Math.hypot(x / 0.72, y) < rad * 0.3) key = x < 0 || y < 0 ? 'c' : 'b';
    setPx(p, r(cx + x), r(cy + y), key);
  }
  return ink(p);
}

/**
 * The War Lord's cape: a heavy fall of cloth from the shoulders to the floor, drawn behind the
 * body. `sway` shears the hem so it trails the stride.
 */
function capePix(G, cx, cy, o = {}) {
  const { w = 15, h = 34, sway = 0, back = false } = o;
  const p = makePix(G.w, G.h);
  const r = Math.round;
  for (let y = 0; y < h; y++) {
    const t = y / (h - 1);
    const half = w * (0.42 + 0.62 * t * t);
    const off = sway * t * t;
    const hem = y > h - 4 ? Math.sin(y * 1.7 + sway) * 1.2 : 0;
    for (let x = -half; x <= half; x += 0.5) {
      const u = x / half;
      // three broad folds, lit from the top-left: the cloth turns, it does not pillow
      const fold = Math.cos(u * 5.6 + 0.7);
      let key = fold > 0.55 ? '6' : fold > -0.05 ? '5' : fold > -0.7 ? '4' : '7';
      if (u < -0.82 || u > 0.86) key = '7';
      if (back && u > -0.12 && u < 0.12) key = '5';
      setPx(p, r(cx + x + off), r(cy + y + hem), key);
    }
  }
  return ink(p);
}

// ------------------------------------------------------------------------------------ composer
const L = (p, x, y, mirror = false) => (p ? { p, x, y, mirror } : null);

/**
 * Compose one frame of a species.
 * @param {object} S species spec
 * @param {'S'|'E'|'N'} f
 * @param {object} o pose {dx,dy,hdx,hdy,legs,legDy,arm,offArm,weapon,offWeapon,weaponBehind,smear,extra}
 */
function frame(S, f, o = {}) {
  const G = S.G;
  const bx = o.dx || 0, by = o.dy || 0;
  const hdx = (o.hdx || 0) + bx, hdy = (o.hdy || 0) + by;
  const legsSet = f === 'E' ? S.legs.E : S.legs.S;
  const legPix = legsSet[o.legs || 'stand'] || legsSet.stand;
  const layers = [];
  const back = S.back && S.back[f];
  const bo = (S.backAt && S.backAt[f]) || [0, 0];
  if (back) layers.push(L(back, bo[0] + bx + (o.backDx || 0), bo[1] + by + (o.backDy || 0)));
  if (o.weaponBehind && o.weapon) layers.push(L(o.weapon, 0, 0));
  layers.push(L(legPix, G.legX, G.legY + (o.legDy || 0)));
  layers.push(L(S.torso[f], S.torsoX[f] + bx, S.torsoY + by));
  if (o.offArm) layers.push(L(limbPix(G, o.offArm.sx + bx, o.offArm.sy + by, o.offArm.hx + bx, o.offArm.hy + by, S.limb), 0, 0));
  if (o.offWeapon) layers.push(L(o.offWeapon, 0, 0));
  const headLayer = L(S.head[f], S.headX[f] + hdx, S.headY + hdy);
  if (f === 'N') {
    if (o.arm) layers.push(L(limbPix(G, o.arm.sx + bx, o.arm.sy + by, o.arm.hx + bx, o.arm.hy + by, S.limb), 0, 0));
    if (o.smear) layers.push(L(o.smear, 0, 0));
    if (o.weapon && !o.weaponBehind) layers.push(L(o.weapon, 0, 0));
    layers.push(headLayer);
  } else {
    layers.push(headLayer);
    if (o.smear) layers.push(L(o.smear, 0, 0));
    if (o.arm) layers.push(L(limbPix(G, o.arm.sx + bx, o.arm.sy + by, o.arm.hx + bx, o.arm.hy + by, S.limb), 0, 0));
    if (o.weapon && !o.weaponBehind) layers.push(L(o.weapon, 0, 0));
  }
  for (const e of o.extra || []) layers.push(e);
  return softenLit(compose(G.w, G.h, layers));
}

// ------------------------------------------------------------------------------------ the rig
// Canonical rig points, expressed once on humanoid.js's 40x40 grid and mapped onto whichever
// canvas the species uses, so a war lord's shoulder sits exactly where a mercenary's would if he
// were that big. `rigDy` drops the whole rig for a short, deep-chested build (the dwarf).
const RIG40 = {
  S: { sh: [16, 15], offSh: [24, 15] },
  E: { sh: [21, 15], offSh: [18, 16] },
  N: { sh: [24, 15], offSh: [16, 15] },
};
const SWING40 = {
  S: [[16, 13, -62], [24, 23, 122], [25, 27, 143], [16, 23, -14]],
  E: [[21, 12, -56], [26, 22, 128], [27, 27, 147], [26, 22, 32]],
  N: [[25, 13, 54], [25, 11, 6], [17, 17, -82], [26, 22, 14]],
};
const STAB40 = {
  S: [[16, 19, -44], [21, 26, 26], [22, 27, 34], [15, 23, -16]],
  E: [[22, 19, 18], [29, 22, 88], [30, 22, 92], [26, 21, 50]],
  N: [[24, 20, -18], [26, 15, 8], [26, 14, 4], [26, 21, 16]],
};
const SMEAR40 = {
  S: { cx: 20, cy: 21, r0: 9, r1: 12, a0: -0.6, a1: 0.5 },
  E: { cx: 21, cy: 20, r0: 9, r1: 12, a0: -0.85, a1: 0.15 },
  N: { cx: 22, cy: 21, r0: 9, r1: 12, a0: -2.15, a1: -0.7 },
};

const shoulder = (S, f) => { const [x, y] = rigPt(S.G, ...RIG40[f].sh); return [x, y + (S.rigDy || 0)]; };
const offShoulder = (S, f) => { const [x, y] = rigPt(S.G, ...RIG40[f].offSh); return [x, y + (S.rigDy || 0)]; };
const armTo = (S, f, hx, hy, o = {}) => { const [sx, sy] = shoulder(S, f); return { sx: sx + (o.dsx || 0), sy: sy + (o.dsy || 0), hx, hy }; };
const offArmTo = (S, f, hx, hy) => { const [sx, sy] = offShoulder(S, f); return { sx, sy, hx, hy }; };
/** The swing/stab path for a species, in its own canvas coordinates. */
function pathFor(S, f) {
  const src = (S.style === 'stab' ? STAB40 : SWING40)[f];
  return src.map(([x, y, a]) => { const [px, py] = rigPt(S.G, x, y); return [px, py + (S.rigDy || 0), a]; });
}
function smearFor(S, f) {
  const m = SMEAR40[f], [cx, cy] = rigPt(S.G, m.cx, m.cy), k = S.G.k;
  return { cx, cy: cy + (S.rigDy || 0), r0: m.r0 * k, r1: m.r1 * k, a0: m.a0, a1: m.a1 };
}

/** Weapon pose at rest, per facing. */
function restWeapon(S, f, o = {}) {
  const r = S.rest[f];
  return S.weapon(f, { gx: r.gx + (o.dx || 0), gy: r.gy + (o.dy || 0), angle: r.a, len: r.len, glint: o.glint || 0 });
}
const restArm = (S, f, dx = 0, dy = 0) => armTo(S, f, S.rest[f].gx + dx, S.rest[f].gy + dy, S.off && S.off[f]);

// ------------------------------------------------------------------------------------ clips
function offHandLayers(S, f, o, dx = 0, dy = 0) {
  if (!S.offRest || !S.offRest[f]) return;
  const r = S.offRest[f];
  o.offArm = offArmTo(S, f, r.gx + dx, r.gy + dy);
  if (S.offWeapon) o.offWeapon = S.offWeapon(f, { gx: r.gx + dx, gy: r.gy + dy, angle: r.a, len: r.len });
}

function idleClip(S, f) {
  const mk = (dy, glint, phase) => {
    const o = { dy, legs: 'stand', arm: restArm(S, f, 0, dy), weapon: restWeapon(S, f, { dy, glint }) };
    offHandLayers(S, f, o, 0, dy);
    if (S.idleExtra) o.extra = S.idleExtra(f, phase, dy);
    return frame(S, f, o);
  };
  return { frames: [mk(0, 0, 0), mk(1, 0, 1), mk(1, 1, 2), mk(0, 0, 3)], durations: [340, 260, 220, 300], loop: true };
}

function walkClip(S, f) {
  const seq = f === 'E'
    ? [['c1', 0, 1, 0], ['c1', 1, 1, 1], ['p1', -1, 0, 0], ['c2', 0, -1, 0], ['c2', 1, -1, 1], ['p2', -1, 0, 0]]
    : [['lfwd', 0, 1, 0], ['lfwd', 1, 1, 1], ['pass', -1, 0, 0], ['rfwd', 0, -1, 0], ['rfwd', 1, -1, 1], ['pass', -1, 0, 0]];
  const frames = seq.map(([legs, dy, hx, hy], i) => {
    const o = { legs, dy, arm: restArm(S, f, hx, dy + hy), weapon: restWeapon(S, f, { dx: hx, dy: dy + hy }) };
    offHandLayers(S, f, o, -hx, dy + hy);
    if (S.idleExtra) o.extra = S.idleExtra(f, i % 4, dy, { sway: hx });
    return frame(S, f, o);
  });
  return { frames, durations: [95, 95, 95, 95, 95, 95], loop: true };
}

function attackClip(S, f) {
  const path = pathFor(S, f);
  const sm = smearFor(S, f);
  const lift = [1, -1, 0, 0], lunge = f === 'E' ? [-1, 3, 3, 1] : [0, 0, 0, 0];
  const legs = ['stand', f === 'E' ? 'c1' : 'lfwd', f === 'E' ? 'c1' : 'lfwd', 'stand'];
  const frames = path.map(([hx, hy, a], i) => {
    const len = S.rest[f].len + (i === 1 ? 1 : 0);
    const o = {
      dy: lift[i], dx: lunge[i], legs: legs[i],
      arm: armTo(S, f, hx, hy, S.off && S.off[f]),
      weapon: S.weapon(f, { gx: hx, gy: hy, angle: a, len }),
      weaponBehind: f === 'N' && i < 2,
    };
    if (i === 1) o.smear = smearArc(makePix(S.G.w, S.G.h), sm.cx, sm.cy, sm.r0, sm.r1, sm.a0, sm.a1, ['a', 'b', 'c', 'd']);
    offHandLayers(S, f, o, i === 1 || i === 2 ? -2 : 0, i === 0 ? -1 : 0);
    if (S.idleExtra) o.extra = S.idleExtra(f, i, lift[i], { sway: i === 1 ? 2 : 0 });
    return frame(S, f, o);
  });
  return { frames, durations: [115, 80, 110, 145], loop: false };
}

function hurtClip(S, f) {
  const lean = f === 'E' ? -2 : 0;
  const o = {
    dx: lean, dy: 1, hdx: lean, hdy: 1, legs: 'stand',
    arm: restArm(S, f, lean, 2), weapon: restWeapon(S, f, { dx: lean, dy: 2 }),
  };
  offHandLayers(S, f, o, lean + 1, 2);
  if (S.idleExtra) o.extra = S.idleExtra(f, 2, 1);
  const recoil = frame(S, f, o);
  return { frames: [solid(recoil, 'F'), recoil], durations: [70, 170], loop: false };
}

/** Facing-independent collapse toward the camera; the weapon falls out of the hand. */
function deathClip(S) {
  const G = S.G, k = G.k, r = S.rest.S;
  const P = (x, y) => rigPt(G, x, y);
  const drop = (gx, gy, a) => S.weapon('S', { gx, gy, angle: a, len: r.len });
  const mk = (o) => frame(S, 'S', { ...o, extra: [...(o.extra || []), ...(S.idleExtra ? S.idleExtra('S', 1, o.dy || 0) : [])] });
  const d = (n) => Math.round(n * k);
  const [h1x, h1y] = P(13, 24), [h2x, h2y] = P(12, 28), [h3x, h3y] = P(12, 32), [h4x, h4y] = P(12, 35);
  const [w1x, w1y] = P(15, 24), [w2x, w2y] = P(15, 29), [w3x, w3y] = P(16, 33), [w4x, w4y] = P(16, 35);
  const f1 = mk({ dy: d(1), hdx: -1, hdy: d(1), legs: 'stand', arm: armTo(S, 'S', h1x, h1y), weapon: drop(w1x, w1y, -34) });
  const f2 = mk({ dy: d(3), hdy: d(4), hdx: -1, legs: 'squat', arm: armTo(S, 'S', h2x, h2y, { dsy: d(3) }), weapon: drop(w2x, w2y, -66) });
  const f3 = mk({ dy: d(6), hdy: d(8), hdx: -1, legs: 'kneel', legDy: d(2), arm: armTo(S, 'S', h3x, h3y, { dsy: d(6) }), weapon: drop(w3x, w3y, -104) });
  const heap = compose(G.w, G.h, [
    L(mk({ dy: d(10), hdy: d(12), hdx: -2, legs: 'down', legDy: d(3), arm: armTo(S, 'S', h4x, h4y, { dsy: d(10) }) }), 0, 0),
    L(drop(w4x, w4y, -108), 0, 0),
  ]);
  const settle = compose(G.w, G.h, [
    L(mk({ dy: d(11), hdy: d(13), hdx: -2, legs: 'down', legDy: d(4), arm: armTo(S, 'S', h4x, h4y + 1, { dsy: d(11) }) }), 0, 0),
    L(drop(w4x, w4y + 1, -108), 0, 0),
  ]);
  return { frames: [f1, f2, f3, heap, settle], durations: [140, 170, 210, 620, 700], loop: false };
}

/** Build every clip of one species: name -> facing -> clip. West mirrors east. */
function buildSpecies(S) {
  const anims = {};
  const put = (name, f, a) => { (anims[name] ||= {})[f] = { name, facing: f, ...a }; };
  for (const f of ['S', 'E', 'N']) {
    put('idle', f, idleClip(S, f));
    put('walk', f, walkClip(S, f));
    put('attack', f, attackClip(S, f));
    put('hurt', f, hurtClip(S, f));
  }
  const d = deathClip(S);
  for (const f of ['S', 'E', 'N']) put('death', f, d);
  for (const name of Object.keys(anims)) {
    const e = anims[name].E;
    anims[name].W = { ...e, facing: 'W', frames: name === 'death' ? e.frames : e.frames.map((p) => mirrorLit(p, '')) };
  }
  return {
    anims, palette: S.palette, w: S.G.w, h: S.G.h, pivot: { x: S.G.px, y: S.G.py },
    emissive: 'YG', scale: 1,
  };
}

// ============================================================================ MERCENARY
// Deliberately the plain one: this is what a soldier looks like when nobody is paying for style.
// Cropped hair under a sweatband, a buff-leather jerkin, ONE strapped steel pauldron on the sword
// shoulder (the other was sold), a plain arming sword hanging point-down and a small round buckler
// held up on the off hand. He is the ruler the other five are measured against.
const MER_HEAD_S = body(`
....................
.......ggffee.......
.....ggfffffee......
.....gffffffee......
.....009999988......
.....3322222211.....
.....32WE22WE11.....
.....3222112211.....
.....3221111211.....
......32111211......
.......321121.......
........2211........`);
const MER_HEAD_E = body(`
....................
......ggffee........
....ggfffffee.......
....gffffffee.......
....00999999888.....
....3322222222......
....32WE222222......
....32222222221.....
....3221111222......
....32211112........
.....3211112........
.......2211.........`);
const MER_HEAD_N = body(`
....................
.......ggffee.......
.....ggfffffee......
.....gffffffee......
.....009999988......
.....gffffffee......
.....gffffffee......
.....gfffffeee......
......ffffeeee......
......fffeeee.......
.......ffeee........
........2211........`);
const MER_TORSO_S = body(`
......................
........655444........
.....cbb655544444.....
...dccb999999994444...
..dccb09999999988444..
..dccb09999999988444..
..6ccb09999999988444..
..665509999999988444..
..665509999999988444..
..889999999999999988..
..88999999gg99999988..
..665555555555554444..
..665555555555554444..
...6555555555554444...
....65555555554444....
.....655555554444.....`);
const MER_TORSO_E = body(`
......................
........655444........
......cbb65554444.....
.....dccb999999944....
.....dccb0999998844...
.....dccb0999998844...
.....6ccb0999998844...
.....665509999988444..
.....665509999988444..
.....8899999999999888.
.....889999gg99999888.
.....6655555555544444.
.....6655555555544444.
......655555555544444.
......65555555554444..
.......5555555444444..`);
const MER_TORSO_N = body(`
......................
........655444........
.....44455556bbc......
...44449999996bccd....
..44889999999900bccd..
..44889999999900bccd..
..44889999999900bcc6..
..4488999999990b5566..
..4488999999990b5566..
..889999999999999988..
..889999999999999988..
..444555555555555566..
..444555555555555566..
...4445555555555566...
....44455555555566....
.....444555555566.....`);
const MERCENARY = {
  G: MAN,
  palette: humanPalette({ skin: '#c99a6e', cloth: '#57683f', leather: '#5c3d24', metal: '#949aa6', accent: '#6b4f2e', eye: '#e8f0ff' }),
  legs: { S: LEGS_S, E: LEGS_E },
  head: { S: MER_HEAD_S, E: MER_HEAD_E, N: MER_HEAD_N }, headX: { S: 14, E: 14, N: 14 }, headY: 6,
  torso: { S: MER_TORSO_S, E: MER_TORSO_E, N: MER_TORSO_N }, torsoX: { S: 13, E: 13, N: 13 }, torsoY: 18,
  limb: { lit: '5', dark: '4', fist: '2', fistLit: '3' },
  style: 'swing',
  rest: { S: { gx: 18, gy: 31, a: 166, len: 13 }, E: { gx: 30, gy: 30, a: 152, len: 13 }, N: { gx: 30, gy: 31, a: 172, len: 13 } },
  offRest: { S: { gx: 34, gy: 30 }, E: { gx: 19, gy: 31 }, N: { gx: 15, gy: 30 } },
  weapon: (f, o) => bladePix(MAN, o.gx, o.gy, o.angle, { len: o.len, w0: 0.9, w1: 0.6, glint: o.glint || 0, guard: 2, grip: '9', pommel: 'e' }),
  offWeapon: (f, o) => bucklerPix(MAN, o.gx, o.gy, 4),
};

// ============================================================================ SWORDSMAN
// The trained duellist: bolt upright where the mercenary slouches, narrow through the shoulders,
// a high collar and a pale sash worn from shoulder to hip, and the LONGEST, slimmest blade of the
// six — carried VERTICAL in front of the face in a formal guard. That straight bright line beside
// the head is the whole read; nothing else in the human family holds a weapon still and upright.
const SWD_HEAD_S = body(`
....................
......00999988......
....009999998888....
...00999999988888...
...00999999998888...
...33222222222111...
....32WE2222WE11....
....322221122211....
....322211122111....
.....3221111211.....
......32111211......
.......321121.......
........2211........`);
const SWD_HEAD_E = body(`
....................
.....009999888......
...00999999888......
..0099999988888.....
..0099999988888.....
..332222222222......
..32WE2222222.......
..3222222222221.....
..3222111122211.....
..32211111222.......
...321111122........
....8321112.........
.....32111..........`);
const SWD_HEAD_N = body(`
....................
......00999988......
....009999998888....
...00999999988888...
...00999999998888...
...00999999998888...
...09999999988888...
...09999999988888...
....999999988888....
.....9999988888.....
......99988888......
.......999888.......
........2211........`);
const SWD_TORSO_S = body(`
......................
........665544........
.....656665554444.....
...6566665555554444...
...65gg665555554444...
...655gg65555554444...
...6555gg5555554444...
...65555gg555554444...
...655555gg55554444...
...8899999999999988...
...88999999gg999988...
...6555555555554444...
...6555555555554444...
....65555555554444....
....65555555554444....
.....655555554444.....`);
const SWD_TORSO_E = body(`
......................
........665544........
......65666555444.....
.....656666555544.....
.....65gg66555544.....
.....655gg6555544.....
.....6555gg555544.....
.....65555gg55544.....
.....655555555544.....
.....889999999988.....
.....88999gg99988.....
.....655555555544.....
.....655555555544.....
......6555555544......
......6555555544......
.......65555544.......`);
const SWD_TORSO_N = body(`
......................
........665544........
.....656665554444.....
...6566665555554444...
...656666555gg54444...
...65666655gg554444...
...6566665gg5554444...
...656666gg55554444...
...65666gg555554444...
...8899999999999988...
...88999999gg999988...
...6555555555554444...
...6555555555554444...
....65555555554444....
....65555555554444....
.....655555554444.....`);

const SWORDSMAN = {
  G: MAN,
  palette: humanPalette({ skin: '#d8ab80', cloth: '#3f5a7e', leather: '#6b5138', metal: '#aab2c0', accent: '#b9c0cc', eye: '#dff2ff' }),
  legs: { S: LEGS_S, E: LEGS_E },
  head: { S: SWD_HEAD_S, E: SWD_HEAD_E, N: SWD_HEAD_N }, headX: { S: 14, E: 14, N: 14 }, headY: 4,
  torso: { S: SWD_TORSO_S, E: SWD_TORSO_E, N: SWD_TORSO_N }, torsoX: { S: 13, E: 13, N: 13 }, torsoY: 17,
  limb: { lit: '2', dark: '1', fist: '2', fistLit: '3' },
  style: 'stab',
  rest: { S: { gx: 19, gy: 30, a: 6, len: 21 }, E: { gx: 29, gy: 29, a: 10, len: 21 }, N: { gx: 30, gy: 30, a: -6, len: 21 } },
  offRest: { S: { gx: 32, gy: 32 }, E: { gx: 20, gy: 32 }, N: { gx: 17, gy: 32 } },
  weapon: (f, o) => bladePix(MAN, o.gx, o.gy, o.angle, { len: o.len, w0: 0.6, w1: 0.4, glint: o.glint || 0, guard: 3, grip: '8', pommel: 'g' }),
};

// ============================================================================ MONK
// The only unarmoured outline in the game's human family, and the only uncut one: one hanging robe
// runs from the shoulder to the floor with nothing strapped, buckled or spiked onto it. A shaved
// skull, ears clear of it, eyes closed, a rope belt, bare feet — and a quarterstaff standing dead
// straight past the top of the sprite. Everything about him points up or down; nothing points out.
const MNK_HEAD_S = body(`
....................
......33222222......
....333222222211....
...33322222222111...
...33222222222211...
..2332222222221111..
..2332EE22222EE111..
..2332222112222111..
...33222111122211...
....332211112211....
.....3221111211.....
........2211........`);
const MNK_HEAD_E = body(`
....................
.....332222222......
...3332222222211....
..333222222222211...
..332222222222221...
.2332222222222211...
.2332EE2222222......
.2332222211222......
..332221111221......
...33221111222......
....3321111222......
.......22111........`);
const MNK_HEAD_N = body(`
....................
......33222222......
....333222222211....
...33322222222111...
...33322222222111...
..2333222222221111..
..2333222222221111..
..2333222222221111..
...33322222222111...
....332222222211....
.....3322222211.....
........2211........`);
const MNK_TORSO_S = body(`
......................
........655444........
.....447777774444.....
...4477777777444444...
..665555555554444444..
..665555555554444444..
..665555777555444444..
..665555777555444444..
..665555755554444444..
..889999999999999988..
..889999900099999988..
..665555555554444444..
..665555777555444444..
..665555777555444444..
.6655557775554444444..
.6655557775554444444..
.6655577775555444444..
.6655577775555444444..
6655557777555544444444
6655557777555544444444
7777777777777777777777
......................`);
const MNK_TORSO_E = body(`
......................
........655444........
......4477777444......
.....447777774444.....
....66555555554444....
....66555555554444....
....66555577754444....
....66555577754444....
....66555577554444....
....8899999999988.....
....8899990099988.....
....66555555554444....
....66555577754444....
....66555577754444....
...6655557775554444...
...6655557775554444...
...6655577755554444...
...6655577755554444...
..665555777755554444..
..665555777755554444..
..777777777777777777..
......................`);

// ============================================================================ DARK WARRIOR
// Black plate with no skin anywhere on it — the point is that you cannot tell what is inside. A
// closed sallet whose only feature is a narrow visor slit with a red ember burning behind it,
// spiked pauldrons, greaves instead of boots, and a heavy dark longsword whose one bright note is
// the lit edge. He is a head taller than the mercenary and reads as a hole in the torchlight.
const DKW_HEAD_S = body(`
....................
.......cdddcc.......
.....ccdddddccb.....
...bccddddddccbba...
..bbccddddddccbbaa..
.abbccdddddccbbbaaa.
.abbccccccccbbbaaaa.
.aaYYaaaaaaaaYYaaaa.
.abbccccccccbbbaaaa.
.abbccccccccbbbaaaa.
..abbcccccccbbbaaa..
..abbcccccccbbbaaa..
...abbccccccbbaaa...
....abbccccbbaaa....`);
const DKW_HEAD_E = body(`
....................
......cdddcc........
....ccdddddccb......
..bccddddddccbbaa...
.bbccddddddccbbaaa..
abbccdddddccbbbaaaa.
abbcccccccccbbbaaa..
aaYYaaaaaaacbbbaaa..
abbccccccccccbbaaa..
abbcccccccccccbaaa..
.abbccccccccccbaa...
.abbcccccccccbaa....
..abbcccccccbaa.....
...abbccccbbaa......`);
const DKW_HEAD_N = body(`
....................
.......cdddcc.......
.....ccdddddccb.....
...bccddddddccbba...
..bbccddddddccbbaa..
.abbccdddddccbbbaaa.
.abbccccccccbbbaaaa.
.abbccccccccbbbaaaa.
.abbccccccccbbbaaaa.
.abbccccccccbbbaaaa.
..abbcccccccbbbaaa..
..abbcccccccbbbaaa..
...abbccccccbbaaa...
....abbccccbbaaa....`);
const DKW_TORSO_S = body(`
......................
........abccba........
.....bbccddccbbaa.....
..cddccbccddccbbbaaa..
.cddcccbccddccbbbbaaa.
.cddcccbccddccbbbbaaa.
..dccbbbccddccbbbaaa..
..bccbbbccddccbbbaaa..
...cbbbccddccbbbaaa...
...cbbbccddccbbbaaa...
..889999999999999988..
..88999999ee99999988..
..abbcccccccccccbbaa..
..abbcccccccccccbbaa..
..abbccccccccccbbbaa..
...abbcccccccccbbaa...
....abbccccccbbbaa....
.....abbccccbbaaa.....`);
const DKW_TORSO_E = body(`
......................
........abccba........
......bbccddccbbaa....
....cddccbccddccbbaa..
....cddcccbccddccbbaa.
....cddcccbccddccbbaa.
.....dccbbbccddccbaa..
.....bccbbbccddccbaa..
......cbbbccddccbbaa..
......cbbbccddccbbaa..
.....889999999999988..
.....88999999ee99988..
.....abbcccccccccbaa..
.....abbcccccccccbaa..
.....abbccccccccbbaa..
......abbcccccccbbaa..
.......abbcccccbbaa...
........abbcccbbaa....`);
const DKW_TORSO_N = body(`
......................
........abccba........
.....bbccddccbbaa.....
..cddccbccddccbbbaaa..
.cddcccbccddccbbbbaaa.
.cddcccbccddccbbbbaaa.
..dccbbbccddccbbbaaa..
..bccbbbccddccbbbaaa..
...cbbbccddccbbbaaa...
...cbbbccddccbbbaaa...
..889999999999999988..
..889999999999999998..
..abbcccccccccccbbaa..
..abbcccccccccccbbaa..
..abbccccccccccbbbaa..
...abbcccccccccbbaa...
....abbccccccbbbaa....
.....abbccccbbaaa.....`);

/** Bare feet under the robe: the boot leather of the shared legs repainted as skin. */
const BAREFOOT = { 8: '1', 9: '2', 0: '3' };
const bare = (set) => Object.fromEntries(Object.entries(set).map(([k, p]) => [k, recolor(p, BAREFOOT)]));

const MONK = {
  G: MAN,
  palette: humanPalette({ skin: '#c99a72', cloth: '#836d43', leather: '#6a5030', metal: '#9aa0a8', accent: '#9c5b36', eye: '#f0e4c8' }),
  legs: { S: bare(LEGS_S), E: bare(LEGS_E) },
  head: { S: MNK_HEAD_S, E: MNK_HEAD_E, N: MNK_HEAD_N }, headX: { S: 14, E: 14, N: 14 }, headY: 6,
  torso: { S: MNK_TORSO_S, E: MNK_TORSO_E, N: MNK_TORSO_S }, torsoX: { S: 13, E: 13, N: 13 }, torsoY: 18,
  limb: { lit: '2', dark: '1', fist: '2', fistLit: '3' },
  style: 'stab',
  rest: { S: { gx: 18, gy: 32, a: 0, len: 34 }, E: { gx: 29, gy: 31, a: 4, len: 34 }, N: { gx: 30, gy: 32, a: -4, len: 34 } },
  offRest: { S: { gx: 31, gy: 33 }, E: { gx: 20, gy: 33 }, N: { gx: 17, gy: 33 } },
  weapon: (f, o) => staffPix(MAN, o.gx, o.gy, o.angle, { len: o.len, glint: o.glint || 0 }),
};

const DARK_WARRIOR = {
  G: MAN,
  palette: humanPalette({ skin: '#5f5a70', cloth: '#33374c', leather: '#3c3448', metal: '#3b4054', accent: '#8e2f34', eye: '#ff5a3a', picks: { metal: [0, 1, 3, 5] } }),
  legs: { S: LEGS_S_PLATE, E: LEGS_E_PLATE },
  head: { S: DKW_HEAD_S, E: DKW_HEAD_E, N: DKW_HEAD_N }, headX: { S: 14, E: 14, N: 14 }, headY: 2,
  torso: { S: DKW_TORSO_S, E: DKW_TORSO_E, N: DKW_TORSO_N }, torsoX: { S: 13, E: 13, N: 13 }, torsoY: 16,
  limb: { lit: 'b', dark: 'a', fist: 'b', fistLit: 'c' },
  style: 'swing',
  rest: { S: { gx: 18, gy: 30, a: -18, len: 17 }, E: { gx: 30, gy: 29, a: 28, len: 17 }, N: { gx: 30, gy: 30, a: 16, len: 17 } },
  weapon: (f, o) => bladePix(MAN, o.gx, o.gy, o.angle, { len: o.len, w0: 1.0, w1: 0.7, glint: o.glint || 0, guard: 2, grip: '8', pommel: 'e', dark: true }),
};

// ============================================================================ DWARVEN GUARD
// Short and WIDE — the widest-for-its-height figure in the game. A brimmed war helm broader than
// the face beneath it (which is nothing but two glints in its shadow), a forked beard falling to
// the belt, a mail hauberk down to the ankles so almost no leg shows at all, and a single-bit
// BEARDED AXE whose crescent is half his own height. Two thirds of his silhouette is helm, beard
// and axe; a player never mistakes that outline for a man.
const DWG_HEAD_S = body(`
....................
.......cccccc.......
.....cccddddccc.....
....bccddddddccb....
...bbccdddddcccbb...
...bbbccccccccbbb...
..abbbbbbbbbbbbbba..
.aaaaaaaaaaaaaaaaaa.
...11WE11bb11EW11...
...1eff112211ffe1...
..eefff112211fffee..
..eeffgg1111ggffee..
..eeeffggggggffeee..
...eeeffgggggffee...
....eeeffggffeee....
....eeff....ffee....
.....eff....ffe.....`);
const DWG_HEAD_E = body(`
....................
......cccccc........
....cccddddccc......
...bccddddddccb.....
..bbccdddddcccbb....
..bbbccccccccbbbb...
.abbbbbbbbbbbbbbba..
aaaaaaaaaaaaaaaaaa..
..1eff11WE111.......
..eefff11221ee......
.eeffgg112211ffe....
.eeffgggg1111ffee...
.eeeffgggggggffee...
..eeeffgggggggfee...
...eeeffgggggfee....
....eeffgggffee.....
.....effggffe.......`);
const DWG_HEAD_N = body(`
....................
.......cccccc.......
.....cccddddccc.....
....bccddddddccb....
...bbccdddddcccbb...
...bbbccccccccbbb...
..abbbbbbbbbbbbbba..
.aaaaaaaaaaaaaaaaaa.
..eeffgggggggffee...
..eeffgggggggffee...
..eeffgggggggffee...
..eeeffgggggffeee...
...eeeffgggffeee....
...eeeffgggffeee....
....eeffgggffee.....
....eeffgggffee.....
.....effgggffe......`);
const DWG_TORSO_S = body(`
......................
........abccba........
...bbccccccccccccbb...
.abbcccccccccccccccbb.
.abbcc4444444444ccbba.
.abbcc6655554444ccbba.
.abbcc6555554444ccbba.
.abbcc6555544444ccbba.
.abb8899999999998bbba.
.abb889999gg99998bbba.
..bbcc6555544444ccbbb.
..bbcc6555544444ccbbb.
..bbcc6555544444ccbbb.
..bbcc6555544444ccbbb.
...bcc6555544444ccbb..
...bcc6555544444ccbb..
....cc655554444ccbb...
.....c65555444ccb.....`);
const DWG_TORSO_E = body(`
......................
........abccba........
....bbccccccccccbb....
...abbccccccccccccbb..
...abbccc4444444cccbb.
...abbccc6655544cccbb.
...abbccc6555444cccbb.
...abbccc6554444cccbb.
...abb88999999999988b.
...abb889999gg99988bb.
....bbbcccccccccccbbb.
....bbbccc4444cccbbbb.
....bbbccc6554cccbbbb.
....bbbccc6544cccbbbb.
....bbbccc6544cccbbbb.
.....bbccc6544ccbbbb..
......bcccc654ccbbb...
.......bccc654ccbb....`);

const DWARVEN_GUARD = {
  G: MAN,
  palette: humanPalette({ skin: '#c08b62', cloth: '#7c3330', leather: '#5b3f28', metal: '#8f96a2', accent: '#a8722e', eye: '#ffe6b0' }),
  legs: { S: LEGS_S, E: LEGS_E },
  head: { S: DWG_HEAD_S, E: DWG_HEAD_E, N: DWG_HEAD_N }, headX: { S: 14, E: 14, N: 14 }, headY: 11,
  torso: { S: DWG_TORSO_S, E: DWG_TORSO_E, N: DWG_TORSO_S }, torsoX: { S: 13, E: 13, N: 13 }, torsoY: 23,
  limb: { lit: '2', dark: '1', fist: '2', fistLit: '3' },
  rigDy: 5,
  style: 'swing',
  rest: { S: { gx: 18, gy: 34, a: -34, len: 12 }, E: { gx: 30, gy: 33, a: 32, len: 12 }, N: { gx: 30, gy: 34, a: 26, len: 12 } },
  weapon: (f, o) => beardAxePix(MAN, o.gx, o.gy, o.angle, { len: o.len, head: 8.5, glint: o.glint || 0, side: f === 'N' ? 1 : -1 }),
};

// ============================================================================ WAR LORD
// The boss of the human family and the deepest human threat in the dungeon. He is drawn on a
// canvas half again as big as everyone else's — 64x72 against 48x48 — so that his 66-px figure
// lands at the SAME texel size as the mercenary's 39-px one instead of being a blown-up copy of a
// smaller man. Four things carry the read, in this order, from across a lit room:
//   1. a tall bladed CREST standing over the helm, taller than a man's head is deep
//   2. PAULDRONS wider than his own stance, with gold on the brow band and the gorget
//   3. a crimson CAPE falling behind him all the way to the floor
//   4. a two-handed GREATSWORD rising across his body past his own shoulder
const WLD_HEAD_S = body(`
............................
.............65.............
............6554............
...........655444...........
...........655444...........
..........65554444..........
..........65554444..........
..........65554444..........
...........655444...........
...........655444...........
............gffe............
.........bccddddccb.........
........bccddddddccb........
.......abbccddddccbba.......
.......abbccddddccbba.......
......ggffffffffffffee......
......aabbYYaaaaYYbbaa......
......aabbYYaaaaYYbbaa......
......abbccccccccccbaa......
......abbccccccccccbaa......
.......abbccccccccbaa.......
.......abbccccccccbaa.......
........abbccccccbaa........
.........abbccccbaa.........`);
const WLD_HEAD_E = body(`
............................
...........65...............
..........6554..............
.........655444.............
.........655444.............
........65554444............
........65554444............
........65554444............
.........655444.............
.........655444.............
..........gffe..............
........bccddddccb..........
.......bccddddddccb.........
......abbccddddccbba........
......abbccddddccbba........
.....ggffffffffffffee.......
.....aabbYYaaaabbbbaa.......
.....aabbYYaaaabbbbaa.......
.....abbccccccccccccbaa.....
.....abbccccccccccccbaa.....
......abbccccccccccbaa......
......abbccccccccccbaa......
.......abbccccccccbaa.......
........abbccccccbaa........`);
const WLD_HEAD_N = body(`
............................
.............65.............
............6554............
...........655444...........
...........655444...........
..........65554444..........
..........65554444..........
..........65554444..........
...........655444...........
...........655444...........
............gffe............
.........bccddddccb.........
........bccddddddccb........
.......abbccddddccbba.......
.......abbccddddccbba.......
......ggffffffffffffee......
......abbccccccccccbaa......
......abbccccccccccbaa......
......abbccccccccccbaa......
......abbccccccccccbaa......
.......abbccccccccbaa.......
.......abbccccccccbaa.......
........abbccccccbaa........
.........abbccccbaa.........`);
const WLD_TORSO_S = body(`
..................................
..........ggffffffffffee..........
.......aabbccccccccccccbbaa.......
...abbccddddccbbbbbbbbccddddccb...
.aabbccdddddccbbbbbbccdddddccbbaa.
.aabbccdddddccbbbbbbccdddddccbbaa.
.aabbccdddddccbggggbbccdddddccbba.
..abbccddddccbggffbbccddddccbbaa..
...abbccdddccbggffbbccdddccbbaa...
....abbccddccbggffbbccddccbbaa....
.....abbcccccbggffbbcccccbbaa.....
......abbcccccbggbbcccccbbaa......
......abbcccccbggbbcccccbbaa......
......abbccccccbbcccccccbbaa......
......abbccccccbbcccccccbbaa......
......abbbccccbbbccccccbbbaa......
.....8899999ggggggg9999998888.....
.....889999999ffff99999998888.....
......aabbcccccccccccccbbbaa......
......aabbcccccccccccccbbbaa......
......aabbccccbbbbccccccbbaa......
......aabbcccbbbbbbcccccbbaa......
.....aabbcccbbbbbbbbcccccbbaa.....
.....aabbcccbbbbbbbbcccccbbaa.....
.....aabbccbbbbbbbbbbccccbbaa.....
.....aabbccbbbbbbbbbbccccbbaa.....
.....aabbccbbbbbbbbbbccccbbaa.....
......aabbbbbbbbbbbbbbbbbbaa......
......aabbbbbbbbbbbbbbbbbbaa......
.......aaaaaaaaaaaaaaaaaaaa.......
..................................
..................................`);
const WLD_TORSO_E = body(`
..................................
.........ggffffffffffee...........
......aabbccccccccccccbbaa........
.....abbccddddccbbbbbbccddddccb...
....aabbccdddddccbbbbccdddddccbba.
....aabbccdddddccbbbbccdddddccbba.
....aabbccdddddccbggbbccdddddccba.
.....abbccddddccbggffbccddddccbba.
......abbccdddccbggffbccdddccbbaa.
.......abbccddcbggffbbccddccbbaa..
........abbcccbggffbbcccccbbaa....
........abbccccbggbbcccccbbaa.....
........abbccccbggbbcccccbbaa.....
........abbcccccbbcccccccbbaa.....
........abbcccccbbcccccccbbaa.....
........abbbcccbbbccccccbbbaa.....
.......8899999ggggggg99999888.....
.......889999999ffff9999988888....
........aabbccccccccccccbbbaa.....
........aabbccccccccccccbbbaa.....
........aabbccccbbbbccccccbbaa....
........aabbcccbbbbbbcccccbbaa....
.......aabbcccbbbbbbbbcccccbbaa...
.......aabbcccbbbbbbbbcccccbbaa...
.......aabbccbbbbbbbbbbccccbbaa...
.......aabbccbbbbbbbbbbccccbbaa...
.......aabbccbbbbbbbbbbccccbbaa...
........aabbbbbbbbbbbbbbbbbbaa....
........aabbbbbbbbbbbbbbbbbbaa....
.........aaaaaaaaaaaaaaaaaaaa.....
..................................
..................................`);
const WLD_CAPE_S = capePix(LORD, 32, 31, { w: 16, h: 36 });
const WLD_CAPE_N = capePix(LORD, 32, 33, { w: 15, h: 34, back: true });

const WAR_LORD = {
  G: LORD,
  palette: humanPalette({ skin: '#6a6152', cloth: '#8e2230', leather: '#4a3a2e', metal: '#666b86', accent: '#c09440', eye: '#ffb24a', picks: { metal: [0, 2, 4, 6] } }),
  legs: { S: LORD_LEGS_S, E: LORD_LEGS_E },
  head: { S: WLD_HEAD_S, E: WLD_HEAD_E, N: WLD_HEAD_N }, headX: { S: 18, E: 18, N: 18 }, headY: 2,
  torso: { S: WLD_TORSO_S, E: WLD_TORSO_E, N: WLD_TORSO_S }, torsoX: { S: 15, E: 15, N: 15 }, torsoY: 26,
  back: { S: WLD_CAPE_S, E: WLD_CAPE_S, N: null }, backAt: { S: [0, 0], E: [-3, 0], N: [0, 0] },
  limb: { lit: 'b', dark: 'a', fist: 'b', fistLit: 'c' },
  style: 'swing',
  rest: { S: { gx: 26, gy: 44, a: 26, len: 30 }, E: { gx: 42, gy: 43, a: 34, len: 30 }, N: { gx: 41, gy: 44, a: 22, len: 30 } },
  offRest: { S: { gx: 31, gy: 47 }, E: { gx: 37, gy: 47 }, N: { gx: 35, gy: 47 } },
  weapon: (f, o) => bladePix(LORD, o.gx, o.gy, o.angle, { len: o.len, w0: 2.0, w1: 1.4, glint: o.glint || 0, guard: 5, grip: '8', pommel: 'g', fuller: true }),
  // the cape from behind is drawn OVER the body: at the north facing it is the whole silhouette
  idleExtra: (f, phase, dy) => (f === 'N' ? [L(WLD_CAPE_N, 0, dy)] : []),
};

// ------------------------------------------------------------------------------------ registry
const cache = new Map();
const build = (key, spec) => () => {
  let b = cache.get(key);
  if (!b) { b = buildSpecies(spec); cache.set(key, b); }
  return b;
};

/**
 * The six trained-fighter sprite builders, keyed by MONSTER_TABLE type. Every key here is a type
 * the game can actually spawn — nothing in this file draws a monster that does not exist.
 * @type {Object<string, () => object>}
 */
export const HUMAN_BUILDERS = {
  'dwarven-guard': build('dwarven-guard', DWARVEN_GUARD),
  'mercenary': build('mercenary', MERCENARY),
  'swordsman': build('swordsman', SWORDSMAN),
  'monk': build('monk', MONK),
  'dark-warrior': build('dark-warrior', DARK_WARRIOR),
  'war-lord': build('war-lord', WAR_LORD),
};

export { buildSpecies, bladePix, beardAxePix, staffPix, bucklerPix, capePix, limbPix, LEGS_S, LEGS_E };
