// humans: the SIX trained fighters of the human family, drawn as HD-2D pixel sprites in the one
// house style (sprites/style.js) — dwarven guard, mercenary, swordsman, monk, dark warrior and the
// War Lord. Every one of them is a real MONSTER_TABLE type; nothing fictional is drawn here.
//
// THE SIX WERE ONE MANNEQUIN RECOLOURED. Every one of them built at 48x48 on pivot (24,45) with
// the same shoulder line, the same head block and the same sword diagonal, so the blue mercenary
// and the brown swordsman were literally the same person in different paint — and two of them were
// blockout-quality next to the creature art: the swordsman was a blue noodle with a stick, the monk
// an unreadable brown blob. They are now differentiated by SILHOUETTE, and the test is the only one
// that counts: render each of them filled solid black and name it. All six pass.
//
//   dwarven guard  THREE TIERS no man can make: a DOMED war helm — a rounded skull, a brow band and
//                  a 20-px brim with the ends turned down into cheek plates — over a forked beard of
//                  18 over a body of 14. Wide, wide, narrow, top to bottom. No face under the brim,
//                  only two catch-lights and a nasal bar; a bearded axe hanging on the off side.
//   mercenary      the ASYMMETRIC one: one strapped pauldron on the sword shoulder, a round buckler
//                  breaking the outline as a disc on the other arm, a plain sword hanging point-down
//                  clear of his leg, and bare legs below a jerkin cut into tabs.
//   swordsman      the LONG COAT, and the only SPLIT hem: a narrow column that bells out below the
//                  belt and then parts into two tapering panels with the boots walking out of the
//                  gap, a leather-faced placket and three brass buttons up the front, and the long
//                  slim blade held LOW, outside the silhouette from grip to point.
//   monk           the only NECK in the cast — a shaved skull on three pixels of bare throat — and
//                  the only free-standing vertical: a quarterstaff PLANTED (its ferrule pinned to
//                  the pivot row whatever the body does above it) and rising past his head, three
//                  columns clear of the robe. Barefoot, a rust stole from shoulder to hip, nothing
//                  strapped or spiked. The calmest outline in the game.
//   dark warrior   TALL AND HORNED: two horns tapering to a point as they sweep up and OUT from a
//                  closed sallet, so the top of his silhouette is the only V in the cast; spiked
//                  pauldrons wider than his stance over a chest that wedges to the belt, and a cloak
//                  widening the base so the wedge stands on a triangle. Two ember slits.
//   war lord       the heaviest human silhouette in the game, and the only one on a bigger canvas:
//                  a crimson plume over a gold-banded helm, pauldrons past his stance, a cape to the
//                  floor and a two-handed greatsword rising clear past his own shoulder.
//
// WHAT MAKES A SILHOUETTE READ, learned the hard way in this file:
//  1. A WEAPON DRAWN INSIDE THE BODY IS NOT IN THE SILHOUETTE. Four of the six carried their blade
//     over their own chest, where a solid-black test sees nothing. Every weapon here now leaves the
//     outline: the swordsman's point falls into empty air, the monk's staff is a separate column,
//     the dark warrior's blade crosses air past his shoulder.
//  2. TWO PIXELS OF AIR IS ONE PIXEL TOO FEW. The house ink is 1 px on each side, so a 2-px gap
//     between two forms closes into solid ink and the two become one blob. Anything meant to read
//     as separate — a staff beside a robe, a horn beside a helm — needs THREE.
//  3. NOTHING ENDS ON A RULED LINE. Every hem here is arched, lobed, split or cut into tabs.
//  4. TWO ROBES ARE ONE ROBE. The monk and the swordsman were both bells, and a bell is a bell
//     whatever colour it is painted; the swordsman's hem had to SPLIT and his front had to grow a
//     placket before the two could be told apart across a room.
//  5. HOUSE INK BELONGS ON THE OUTSIDE. `houseOutline` keeps interior ink as drawing — correctly —
//     so a sleeve that arrives carrying its own black ring scribbles that ring across the chest it
//     lies on. `limbPix(..., { edge })` outlines an arm in one step of the GARMENT's own ramp
//     instead: cloth on cloth, plate on plate, ink only where the figure meets the air.
//
// TWO CANVASES, ONE PIXEL DENSITY
//   MAN   48x48, pivot (24,45) — the five ordinary fighters, figures 35-44 px.
//   LORD  64x72, pivot (32,68) — the War Lord alone, figure 67 px.
// style.js SCALE says how tall each creature stands relative to the hero and `sizeFor` turns that
// into the billboard multiplier; drawing the War Lord at 66 px instead of squeezing him onto the
// 40-px canvas the other humans use is what keeps his texels the same size as everyone else's
// (0.86x) instead of double-size mush (2.11x). Every figure here lands in a 0.86-1.19 band.
//
// SHARED KEY VOCABULARY (identical to humanoid.js, so the two files read as one cast):
//   # outline (house INK)   @ lit edge      1 2 3 skin dark->light
//   7 4 5 6 cloth (7 = darkest crease)      8 9 0 leather      a b c d metal (+d specular)
//   e f g accent            T bone   E eye socket   W eye catch-light   Y glow (emissive)
//   G glint (emissive)      F hurt flash
// Ramps come from style.ramp(): shadows drift violet and gain saturation, highlights drift amber
// and lose a little. The key light is TOP-LEFT on every facing. Bodies are drawn WITHOUT their
// outline and inked by `ink()` afterwards, so the silhouette is exactly one pixel everywhere and
// softens to '@' on the edges that face the light.
//
// SHAPE FIRST, SHADING SECOND — WITH ONE EXCEPTION. Cloth blocks (the coat, the robe, the hauberk)
// are typed as FLAT shapes in one key and re-lit by `keyed()` (pixelPainter.keyShade) off the house
// top-left terminator: hand-typing a value into every pixel of a 22-px-wide coat is how the old art
// ended up pillow-shaded and how rows ended up the wrong width. But `keyShade` RE-KEYS every pixel
// holding one of the ramp keys it is given, so structure drawn in those keys is erased — a coat's
// front edge typed in '7' simply disappears. Two consequences, both used here: structure inside a
// re-lit block is drawn in a DIFFERENT vocabulary (the swordsman's placket in leather, his buttons
// and the monk's stole in accent), and the Dark Warrior's plate — which is all structure and no
// cloth — is hand-valued with `body()` instead, one lit pixel of the top step down every top-left
// facing edge and the ramp running left to right across the form.
//
// FACINGS south / east / north are each drawn; west is the mirrored east.
// CLIPS idle(4) walk(6) attack(4) hurt(2) death(5).
import {
  Palette, paint, compose, mirrorLit, outline, houseOutline, keyShade, line, setPx, solid, makePix, smearArc, recolor, clone,
} from '../pixelPainter.js';
import { INK, INK_LIT, LIT, ramp } from '../style.js';

// ------------------------------------------------------------------------------------ geometry
/** @typedef {{w:number,h:number,px:number,py:number,legX:number,legY:number,k:number}} Geom */

/** The ordinary-fighter canvas. `k` is the rig scale against humanoid.js's 40x40 rig. */
export const MAN = { w: 48, h: 48, px: 24, py: 45, legX: 15, legY: 33, k: 1 };
/** The War Lord's canvas: the same pixel density, more of it. */
export const LORD = { w: 64, h: 72, px: 32, py: 68, legX: 19, legY: 56, k: 1.65 };

/** Map a humanoid.js rig point (on its 40x40, pivot (20,37) canvas) onto a geometry. */
const rigPt = (G, x, y) => [Math.round(G.px + (x - 20) * G.k), Math.round(G.py + (y - 37) * G.k)];

// ------------------------------------------------------------------------------------ palette
// `ramp()` builds seven house steps; each vocabulary picks the ones it needs so a 3-key ramp is a
// slice of the same curve as a 4-key one and every species shares one contrast law.
// The house hue-shift is deliberately strong; over a SEVEN step ramp it will walk an olive all the
// way round to green, so the shift is dialled to the same figure the shipping cast uses (0.02) and
// each vocabulary takes the slice of the curve its material actually occupies: cloth and skin live
// in the middle (they are dyed and pigmented, not polished), metal reaches the top because a
// specular highlight is the whole point of steel, and leather sits between them.
const RAMP_OPTS = { hueShift: 0.02, satShift: 0.06 };
const RAMP_PICK = { skin: [1, 3, 5], cloth: [0, 2, 3, 4], leather: [1, 3, 4], metal: [1, 3, 5, 6], accent: [1, 3, 5] };

/**
 * One species palette over the shared key vocabulary. `picks` overrides which steps of the
 * seven-step house ramp a material takes — the Dark Warrior's plate is the same curve as the
 * Swordsman's, read from four steps lower down.
 * @param {{skin:string, cloth:string, leather:string, metal:string, accent:string, eye:string,
 *   tooth?:string, picks?:Object<string, number[]>}} o
 */
export function humanPalette(o) {
  const p = new Palette().set('#', INK).set('@', INK_LIT);
  const put = (keys, base, which) => {
    const r = ramp(base, 7, RAMP_OPTS);
    const pick = (o.picks && o.picks[which]) || RAMP_PICK[which];
    [...keys].forEach((k, i) => p.set(k, r[pick[i]]));
  };
  put('123', o.skin, 'skin');
  put('7456', o.cloth, 'cloth');   // 7 is the darkest crease, then 4 5 6 up to the lit fold
  put('890', o.leather, 'leather');
  // `s` is THE SOLE: the bottom step of the leather ramp, one below the darkest boot tone, so the
  // last row of every boot is in true contact shadow instead of borrowing the trouser colour.
  p.set('s', ramp(o.leather, 7, RAMP_OPTS)[0]);
  put('abcd', o.metal, 'metal');   // d is a 1-px specular only
  put('efg', o.accent, 'accent');
  return p
    .set('T', o.tooth || '#ded2b8')
    .set('E', '#191322')
    .set('W', '#e6dcc8')
    .set('Y', o.eye)
    .set('G', '#efe9dd')
    .set('F', '#fff4f0');
}

// ------------------------------------------------------------------------------------ inking
const LIGHT_KEYS = new Set(['3', '6', '0', 'c', 'd', 'g', 'T', 'W'].map((c) => c.charCodeAt(0)));

/** Ink a hand-drawn body part: one-pixel house outline, softened to '@' on the lit edges. */
const ink = (p) => outline(p, '#', { lit: LIT, litKey: '@' });
/** Ink a block written as rows of keys (no outline characters in the source art). */
const body = (rows) => ink(paint(rows));
/**
 * The same, but RE-SHADED to the house key light first (pixelPainter.keyShade): the pixels holding
 * `keys` are re-keyed off a top-left terminator — highlight on the upper-left third, core shadow on
 * the lower-right third, reflected light as one cooler pixel on the bottom-right rim. Use it on any
 * block whose hand-typed shading rings the form (dark at BOTH edges, bright down the middle), which
 * is pillow shading and is banned by style.js.
 */
const keyed = (rows, keys, o = {}) => ink(keyShade(paint(rows), keys, { lit: LIT, ...o }));

/** Soften a composed frame's remaining hard outline where a light tone meets empty space top-left. */
function softenLit(p) {
  const o = { w: p.w, h: p.h, d: new Uint16Array(p.d) };
  const HASH = 35, AT = 64;
  for (let y = 0; y < p.h; y++) for (let x = 0; x < p.w; x++) {
    if (p.d[y * p.w + x] !== HASH) continue;
    const inR = x + 1 < p.w ? p.d[y * p.w + x + 1] : 0, inD = y + 1 < p.h ? p.d[(y + 1) * p.w + x] : 0;
    const outL = x > 0 ? p.d[y * p.w + x - 1] : 0, outU = y > 0 ? p.d[(y - 1) * p.w + x] : 0;
    if ((LIGHT_KEYS.has(inR) && !outL) || (LIGHT_KEYS.has(inD) && !outU)) o.d[y * p.w + x] = AT;
  }
  return o;
}

// ------------------------------------------------------------------------------------ legs
// The house leg vocabulary, 18x12, stamped at (G.legX, G.legY): two 3-px legs with a 2-px gap and
// boots flaring outward, the screen-left leg carrying the lit tones. Copied key-for-key from
// humanoid.js so a mercenary and a rogue plant their feet the same way — one cast, one walk.
// Everything above the knee is covered by a hauberk, a robe or a skirt of plate on four of these
// six, so what actually shows is the boot; the poses still drive it.
//
// EVERY BOOT ENDS IN FIVE STEPS, and none of them is a straight line. The old block ran the shin
// straight into a leather rectangle and finished it with `..######..######` — a flat six-pixel cut
// with no sole, no toe and no ankle, so six of the cast looked sawn off at the floor. The law now:
//
//   ANKLE  the shin pulls IN by a pixel  (`.....#65#`)   — the break that says there is a joint
//   CUFF   the boot steps back OUT over it               — the overhang that says it is a boot
//   VAMP   the foot widens away from the body            — the instep
//   TOE    one more pixel out, one step darker           — which way the foot points
//   SOLE   `s`, the bottom step of the leather ramp, pulled in a pixel at the HEEL
//   then the house outline pass lays the 1-px ink shadow under the sole: the weight.
//
// The block is 18 wide (it was 16) purely so the toes have room to point outward without the ink
// falling off the edge of the stamp; `MAN.legX` moved from 16 to 15 to keep it centred on the rig.
const LEGS_S = {
  stand: paint(`
....#655#..#554#..
....#655#..#554#..
....#665#..#554#..
....#655#..#544#..
....#665#..#554#..
.....#65#..#54#...
....#009#..#988#..
....#009#..#988#..
...#0099#..#9888#.
..#00998#..#98888#
..#ssss#....#ssss#
...####......####.`),
  lfwd: paint(`
....#655#..#554#..
....#655#..#554#..
....#665#..#554#..
....#655#..#54#...
....#665#..#988#..
.....#65#..#988#..
....#009#..#9888#.
....#009#..#98888#
...#0099#...#ssss#
..#00998#....####.
..#ssss#..........
...####...........`),
  rfwd: paint(`
....#655#..#554#..
....#655#..#554#..
....#665#..#554#..
.....#65#..#544#..
....#009#..#554#..
....#009#..#54#...
...#0099#..#988#..
..#00998#..#988#..
..#ssss#...#9888#.
...####....#98888#
............#ssss#
.............####.`),
  pass: paint(`
....#655#..#554#..
....#655#..#554#..
....#665#..#554#..
....#655#..#544#..
.....#65#..#54#...
....#009#..#988#..
....#009#..#988#..
...#0099#..#9888#.
..#00998#..#98888#
..#ssss#....#ssss#
...####......####.
..................`),
  squat: paint(`
..................
..................
..................
...#655#..#554#...
..#655#....#554#..
..#009#....#988#..
.#0099#....#9888#.
.#00998#..#98888#.
..#ssss#...#ssss#.
...####.....####..
..................
..................`),
  kneel: paint(`
..................
..................
..................
...#655#.#554#....
...#655#.#554#....
...#009#.#988#....
..#0099#.#9888#...
..#00998#98888#...
..#sssss#sssss#...
...#####.#####....
..................
..................`),
  down: paint(`
..................
..................
..................
..................
..................
...#655#..#554#...
...#009#..#988#...
..#0099#..#9888#..
..#00998##98888#..
..#sssss##sssss#..
...#####..#####...
..................`),
};

const LEGS_E = {
  stand: paint(`
.....#4#554#......
.....#4#554#......
.....#4#554#......
.....#4#554#......
.....#4#554#......
.....#4##54#......
.....#8#009#......
.....#8#009#......
....#88#0099#.....
....#88#00998#....
....#ss##ssss#....
.....##...####....`),
  c1: paint(`
.....#4#554#......
.....#4#554#......
.....#4#554#......
.....#4#.#54#.....
.....#4#..#554#...
.....#4#..#54#....
.....#8#..#009#...
.....#8#..#009#...
....#88#..#0099#..
....#88#..#00998#.
....#ss#...#ssss#.
.....##.....####..`),
  p1: paint(`
.....#4#554#......
.....#4#554#......
.....#4#554#......
.....#4#554#......
.....#4#554#......
.....#8#554#......
.....#8#009#......
....#88#009#......
....#88#0099#.....
....#ss#00998#....
.....##.#ssss#....
.........####.....`),
  c2: paint(`
.....#4#554#......
.....#4#554#......
.....#4#554#......
.....#4#554#......
....#4#.#554#.....
...#4#..#54#......
...#8#..#009#.....
..#8#...#009#.....
..#88#..#0099#....
..#88#..#00998#...
..#ss#...#ssss#...
...##.....####....`),
  p2: paint(`
.....#4#554#......
.....#4#554#......
.....#4#554#......
.....#4#554#......
.....#4#554#......
.....#8#554#......
....#88#009#......
....#88#009#......
....#ss#0099#.....
.....##.#00998#...
.........#ssss#...
..........####....`),
};
LEGS_E.squat = LEGS_S.squat; LEGS_E.kneel = LEGS_S.kneel; LEGS_E.down = LEGS_S.down;

/** The same walk in plate: cloth and leather keys swapped for the metal ramp (dark warrior). */
const PLATE = { 4: 'a', 5: 'b', 6: 'c', 7: 'a', 8: 'a', 9: 'b', 0: 'c', s: 'a' };
const plated = (set) => Object.fromEntries(Object.entries(set).map(([k, p]) => [k, recolor(p, PLATE)]));
const LEGS_S_PLATE = plated(LEGS_S), LEGS_E_PLATE = plated(LEGS_E);

// The War Lord stands on a bigger floor: 26x12 greaves and sabatons under a skirt of plate, drawn
// at his own scale so his boots are as heavy as the rest of him.
// The same five steps as the ordinary boot, at the War Lord's scale: the greave narrows into the
// ankle, the sabaton overhangs it, the toe pushes out and the sole is a band of the darkest metal
// with the heel lifted a pixel. Nothing here finishes on `##########` any more.
const LORD_LEGS_S = {
  stand: paint(`
....#cbbb#....#bbba#.....
....#cbbb#....#bbba#.....
....#cbbb#....#bbba#.....
....#ccbb#....#bbaa#.....
...#ccbbb#..#bbbaaa#.....
...#cbbbb#..#bbbaaa#.....
....#cbbb#..#bbaaa#......
..#ccbbbb#..#bbaaaaa#....
.#ccbbbbb#..#bbaaaaaa#...
#ccbbbbbb#..#bbaaaaaaa#..
#aaaaaaa#....#aaaaaaaa#..
.#######......########...`),
  lfwd: paint(`
....#cbbb#....#bbba#.....
....#cbbb#....#bbba#.....
....#cbbb#...#bbaa#......
....#ccbb#...#bbaa#......
...#ccbbb#...#bbaa#......
...#cbbbb#..#bbaaaa#.....
....#cbbb#.#bbaaaaa#.....
..#ccbbbb#.#bbaaaaaa#....
.#ccbbbbb#..#aaaaaaa#....
#ccbbbbbb#...########....
#aaaaaaa#................
.#######.................`),
  pass: paint(`
....#cbbb#....#bbba#.....
....#cbbb#....#bbba#.....
....#cbbb#....#bbba#.....
....#ccbb#....#bbaa#.....
...#ccbbb#...#bbaaa#.....
....#cbbb#...#bbaa#......
..#ccbbbb#..#bbaaaa#.....
.#ccbbbbb#..#bbaaaaa#....
#ccbbbbbb#..#bbaaaaaa#...
#aaaaaaa#....#aaaaaaa#...
.#######......#######....
.........................`),
};
LORD_LEGS_S.rfwd = mirrorLit(LORD_LEGS_S.lfwd, 'ac');
const LORD_LEGS_E = {
  stand: paint(`
......#ba#.#cbbb#........
......#ba#.#cbbb#........
......#ba#.#cbbb#........
......#ba#.#ccbb#........
.....#bba#.#ccbbb#.......
.....#bba#.#cbbbb#.......
.....#bba#..#cbbb#.......
.....#bba#.#ccbbbbb#.....
....#bbaa#.#ccbbbbbb#....
....#bbaa#.#cbbbbbbbb#...
....#aaa#..#aaaaaaaaa#...
.....###....#########....`),
  c1: paint(`
......#ba#.#cbbb#........
......#ba#.#cbbb#........
......#ba#..#cbbb#.......
......#ba#..#ccbb#.......
.....#bba#..#ccbbb#......
.....#bba#..#cbbbb#......
.....#bba#...#cbbb#......
.....#bba#..#ccbbbbb#....
....#bbaa#..#ccbbbbbb#...
....#bbaa#..#cbbbbbbbb#..
....#aaa#....#aaaaaaaa#..
.....###......########...`),
  p1: paint(`
......#ba#.#cbbb#........
......#ba#.#cbbb#........
......#ba#.#cbbb#........
.....#bba#.#ccbb#........
.....#bba#.#ccbbb#.......
.....#bba#.#cbbbb#.......
....#bbaa#..#cbbb#.......
....#bbaa#.#ccbbbbb#.....
....#aaa#..#ccbbbbbb#....
.....###...#cbbbbbbbb#...
...........#aaaaaaaaa#...
............#########....`),
};
LORD_LEGS_E.c2 = LORD_LEGS_E.c1; LORD_LEGS_E.p2 = LORD_LEGS_E.p1;
const LORD_COLLAPSE = {
  squat: paint(`
.........................
.........................
....#cbbb#....#bbba#.....
...#ccbbb#....#bbaaa#....
....#cbbb#....#bbaa#.....
..#ccbbbb#....#bbaaaa#...
.#ccbbbbb#....#bbaaaaa#..
#ccbbbbbb#....#bbaaaaaa#.
#aaaaaaa#......#aaaaaaa#.
.#######........#######..
.........................
.........................`),
  kneel: paint(`
.........................
.........................
.........................
...#cbbb#..#bbba#........
..#ccbbb#..#bbaaa#.......
.#ccbbbb#..#bbaaaa#......
.#cbbbbb#..#bbaaaaa#.....
#ccbbbbb#..#bbaaaaaa#....
#cbbbbbbbbbbbbaaaaaa#....
#aaaaaaaaaaaaaaaaaaa#....
.###################.....
.........................`),
  down: paint(`
.........................
.........................
.........................
.........................
...#cbbb#....#bbba#......
..#ccbbb#....#bbaaa#.....
.#ccbbbb#....#bbaaaa#....
.#cbbbbbbb##bbbaaaaa#....
#cbbbbbbbbbbbbbaaaaaa#...
#aaaaaaaaaaaaaaaaaaaa#...
.####################....
.........................`),
};
Object.assign(LORD_LEGS_S, LORD_COLLAPSE);
Object.assign(LORD_LEGS_E, LORD_COLLAPSE);

// ------------------------------------------------------------------------------------ limbs
/**
 * A 2-px limb from shoulder (sx,sy) to hand (hx,hy), with a fist at the hand (4 px on the War
 * Lord's larger rig). `edge` outlines it in a ramp key instead of house ink — see below.
 * @param {Geom} G @param {{lit?:string, dark?:string, fist?:string, fistLit?:string, r?:number, edge?:string}} k
 */
function limbPix(G, sx, sy, hx, hy, k = {}) {
  const p = makePix(G.w, G.h);
  const lit = k.lit || '2', dark = k.dark || '1', fist = k.fist || '2', fistLit = k.fistLit || '3';
  line(p, sx, sy, hx, hy, lit);
  line(p, sx + 1, sy, hx + 1, hy, dark);
  if (G.k > 1.2) { line(p, sx - 1, sy, hx - 1, hy, lit); line(p, sx + 2, sy, hx + 2, hy, dark); }
  const r = k.r ?? (G.k > 1.2 ? 2 : 1);
  for (let y = -r; y <= r; y++) for (let x = -r; x <= r; x++) setPx(p, hx + x, hy + y, (x < 0 || y < 0) ? fistLit : fist);
  // A LIMB LAID OVER ITS OWN GARMENT IS NOT A SILHOUETTE EDGE. The house ink is for the outside of
  // the figure; ringing a sleeve in it where the sleeve lies on the chest scribbles a black line
  // across the body (`houseOutline` keeps interior ink, correctly, as drawing). `edge` names a
  // ramp key to outline with instead — one step down the garment's own ramp, which separates the
  // arm from the robe without putting a hole in it.
  return k.edge ? outline(p, k.edge) : ink(p);
}

// ------------------------------------------------------------------------------------ weapons
// Every weapon is marched along its own axis with a FILLED cross-section at each step: two
// Bresenham lines interleave into a checkerboard on diagonals, and a hollow section combs into a
// fork. `w0`/`w1` are the half-widths at the guard and at the tip, so the same code draws the
// swordsman's needle and the war lord's slab.
/**
 * A straight blade. `fuller` runs a shadow groove down the middle of a wide one, which is what
 * stops a greatsword reading as a plank.
 * @param {Geom} G
 */
function bladePix(G, gx, gy, angle, o = {}) {
  const { len = 12, w0 = 0.6, w1 = 0.6, glint = 0, grip = '9', pommel = 'e', guard = 0, fuller = false } = o;
  const p = makePix(G.w, G.h);
  const a = (angle * Math.PI) / 180;
  const dx = Math.sin(a), dy = -Math.cos(a);
  const nx = -dy, ny = dx;
  const r = Math.round;
  const bx = gx + dx * 2.2, by = gy + dy * 2.2;
  const steps = Math.max(6, Math.round(len * 2.6));
  const edgeLit = 'd', faceLit = 'c', faceDark = 'b';
  for (let i = 0; i <= steps; i++) {
    const t = i / steps;
    const cx = bx + dx * len * t, cy = by + dy * len * t;
    const hw = w0 + (w1 - w0) * t;
    for (let u = -hw; u <= hw; u += 0.3) {
      let key = u < -hw + 0.8 ? faceLit : u > hw - 0.8 ? 'a' : faceDark;
      if (fuller && Math.abs(u) < hw * 0.3) key = 'a';
      setPx(p, r(cx + nx * u), r(cy + ny * u), key);
    }
  }
  setPx(p, r(bx + dx * len), r(by + dy * len), edgeLit);
  setPx(p, r(bx + dx * len * 0.7 - nx * (w0 + (w1 - w0) * 0.7)), r(by + dy * len * 0.7 - ny * (w0 + (w1 - w0) * 0.7)), edgeLit);
  if (glint > 0) {
    const t = 0.34 + glint * 0.3;
    for (let k = 0; k < 2; k++) setPx(p, r(bx + dx * len * t + dx * k - nx * (w0 + (w1 - w0) * t)), r(by + dy * len * t + dy * k - ny * (w0 + (w1 - w0) * t)), 'G');
  }
  if (guard) for (let k = -guard; k <= guard; k++) setPx(p, r(bx - dx * 0.9 + nx * k), r(by - dy * 0.9 + ny * k), k <= -1 ? 'g' : k === 0 ? 'f' : 'e');
  const gripLen = Math.max(3, Math.round(2.6 * G.k));
  for (let k = 0; k < gripLen; k++) setPx(p, r(gx - dx * k), r(gy - dy * k), k === gripLen - 1 ? pommel : grip);
  return ink(p);
}

/**
 * A BEARDED AXE: one heavy crescent bit hanging off the near side of the haft, its cutting edge
 * bellying down well below the eye. A double-bit head is the barbarian's; this asymmetric hook is
 * the dwarf's, and the two never read as the same weapon.
 * @param {Geom} G
 */
function beardAxePix(G, gx, gy, angle, o = {}) {
  const { len = 16, head = 9, glint = 0, side = -1 } = o;
  const p = makePix(G.w, G.h);
  const a = (angle * Math.PI) / 180;
  const dx = Math.sin(a), dy = -Math.cos(a);
  const nx = -dy, ny = dx;
  const r = Math.round;
  const steps = Math.max(8, Math.round(len * 2.6));
  for (let i = 0; i <= steps; i++) {
    const t = i / steps;
    setPx(p, r(gx + dx * len * t), r(gy + dy * len * t), '9');
    setPx(p, r(gx + dx * len * t + nx * 0.9), r(gy + dy * len * t + ny * 0.9), '8');
  }
  setPx(p, r(gx - dx * 1.8), r(gy - dy * 1.8), 'e');
  setPx(p, r(gx - dx * 2.8), r(gy - dy * 2.8), 'f');
  // The bit is a true CRESCENT: an annulus centred inside the haft on the far side, so the cutting
  // edge bows out and the beard hooks back down toward the hands. Drawn by scanning the box the
  // crescent can occupy — an ellipse-minus-ellipse reads as an axe at 8 px where an outline blob
  // reads as a mitten.
  const ex = gx + dx * (len - 1.5), ey = gy + dy * (len - 1.5);
  const cx = ex - nx * head * 0.42 * side, cy = ey - ny * head * 0.42 * side;
  const rOut = head * 1.06, rIn = head * 0.46;
  for (let py = -Math.ceil(rOut) - 1; py <= Math.ceil(rOut) + 1; py++) {
    for (let px = -Math.ceil(rOut) - 1; px <= Math.ceil(rOut) + 1; px++) {
      const d = Math.hypot(px, py);
      if (d > rOut || d < rIn) continue;
      // keep only the half-disc that hangs off `side` of the haft, biased back toward the grip
      const along = (px * dx + py * dy) / (d || 1), across = ((px * nx + py * ny) / (d || 1)) * side;
      if (across < -0.12) continue;
      if (along > 0.72) continue;
      const t = (d - rIn) / (rOut - rIn);
      let key = t > 0.9 ? 'd' : t > 0.62 ? 'c' : t > 0.28 ? 'b' : 'a';
      if (along < -0.66) key = t > 0.7 ? 'b' : 'a';           // the beard, turned away from the light
      setPx(p, r(cx + px), r(cy + py), key);
    }
  }
  // the eye: the haft passes through the head
  for (let t = -1.2; t <= 1.8; t += 0.4) setPx(p, r(ex + dx * t), r(ey + dy * t), '9');
  if (glint > 0) setPx(p, r(cx + nx * rOut * 0.86 * side - dx * rOut * 0.3), r(cy + ny * rOut * 0.86 * side - dy * rOut * 0.3), 'G');
  return ink(p);
}

/**
 * A quarterstaff: a plain shaft with an iron ferrule at each end and a bound grip. The grip sits a
 * third of the way up, so the staff towers over the monk's head — the calm vertical that makes his
 * silhouette unmistakable.
 * @param {Geom} G
 */
function staffPix(G, gx, gy, angle, o = {}) {
  const { len = 26, glint = 0 } = o;
  const a = (angle * Math.PI) / 180;
  const dx = Math.sin(a), dy = -Math.cos(a);
  const nx = -dy, ny = dx;
  const p = makePix(G.w, G.h);
  const r = Math.round;
  // `down` may be given explicitly so the FERRULE STAYS PLANTED while the body breathes above it:
  // the legs are drawn at a fixed row and the torso is not, so a staff measured from the grip alone
  // lifts off the floor (or sinks through it) on half the idle frames.
  const down = o.down ?? len * 0.34, up = o.up ?? (len - down);
  const steps = Math.round(len * 2.6);
  for (let i = 0; i <= steps; i++) {
    const t = -down + (up + down) * (i / steps);
    const cx = gx + dx * t, cy = gy + dy * t;
    const end = t > up - 2.2 || t < -down + 2.2;
    setPx(p, r(cx - nx * 0.5), r(cy - ny * 0.5), end ? 'c' : '0');
    setPx(p, r(cx + nx * 0.5), r(cy + ny * 0.5), end ? 'a' : '9');
  }
  for (let t = -2.2; t <= 2.2; t += 0.4) {            // the bound grip
    setPx(p, r(gx + dx * t - nx * 0.5), r(gy + dy * t - ny * 0.5), 'f');
    setPx(p, r(gx + dx * t + nx * 0.5), r(gy + dy * t + ny * 0.5), 'e');
  }
  if (glint > 0) setPx(p, r(gx + dx * (up - 1.4) - nx * 0.5), r(gy + dy * (up - 1.4) - ny * 0.5), 'G');
  return ink(p);
}

/**
 * A round buckler: rim, boss and a lit crescent (the mercenary's off hand). `aspect` is how wide
 * the disc is against its height — 0.72 is a shield turned edge-on, 0.86 is one held square to
 * the camera, which is what it takes for the shape to read as a SHIELD in a silhouette rather
 * than as a lump on his hip.
 */
function bucklerPix(G, cx, cy, rad = 5, { aspect = 0.72 } = {}) {
  const p = makePix(G.w, G.h);
  const r = Math.round;
  for (let y = -rad; y <= rad; y++) for (let x = -rad * aspect; x <= rad * aspect; x += 0.5) {
    const d = Math.hypot(x / aspect, y) / rad;
    if (d > 1) continue;
    let key = d > 0.86 ? '8' : d > 0.72 ? '9' : '0';
    if (x < 0 && y < 0 && d > 0.72) key = '0';
    if (Math.hypot(x / aspect, y) < rad * 0.3) key = x < 0 || y < 0 ? 'c' : 'b';
    setPx(p, r(cx + x), r(cy + y), key);
  }
  return ink(p);
}

/**
 * The War Lord's cape: a heavy fall of cloth from the shoulders to the floor, drawn behind the
 * body. `sway` shears the hem so it trails the stride.
 */
function capePix(G, cx, cy, o = {}) {
  const { w = 15, h = 34, sway = 0, back = false } = o;
  const p = makePix(G.w, G.h);
  const r = Math.round;
  // THE HEM IS NOT A RULED LINE. It used to be: `Math.sin(y * 1.7)` nudged whole ROWS up and down
  // by a pixel, which rounds away to nothing, so the War Lord's cloak stopped dead on one flat
  // horizontal cut across the full width of the sprite — and it hung low enough to bury his
  // sabatons, so the biggest figure in the game had no feet at all. The scallop now runs across
  // the WIDTH (`hemAt(u)`, up to 4 px of cloth missing between the points of the hem) and the last
  // two rows of every column go one step darker: the cloth doubles back on itself and has weight.
  const hemAt = (u) => 1.9 + 2.0 * Math.cos(u * 7.3 + 1.1) * Math.cos(u * 2.1);
  for (let y = 0; y < h; y++) {
    const t = y / (h - 1);
    const half = w * (0.42 + 0.62 * t * t);
    const off = sway * t * t;
    for (let x = -half; x <= half; x += 0.5) {
      const u = x / half;
      const cut = hemAt(u);
      if (y > h - 1 - cut) continue;
      // three broad folds, lit from the top-left: the cloth turns, it does not pillow
      const fold = Math.cos(u * 5.6 + 0.7);
      let key = fold > 0.55 ? '6' : fold > -0.05 ? '5' : fold > -0.7 ? '4' : '7';
      if (u < -0.82 || u > 0.86) key = '7';
      if (back && u > -0.12 && u < 0.12) key = '5';
      if (y > h - 3.2 - cut) key = '7';                 // the turned hem, in its own shadow
      setPx(p, r(cx + x + off), r(cy + y), key);
    }
  }
  return ink(p);
}

// ------------------------------------------------------------------------------------ composer
const L = (p, x, y, mirror = false) => (p ? { p, x, y, mirror } : null);

/**
 * Compose one frame of a species.
 * @param {object} S species spec
 * @param {'S'|'E'|'N'} f
 * @param {object} o pose {dx,dy,hdx,hdy,legs,legDy,arm,offArm,weapon,offWeapon,weaponBehind,smear,extra}
 */
function frame(S, f, o = {}) {
  const G = S.G;
  const bx = o.dx || 0, by = o.dy || 0;
  const hdx = (o.hdx || 0) + bx, hdy = (o.hdy || 0) + by;
  const legsSet = f === 'E' ? S.legs.E : S.legs.S;
  const legPix = legsSet[o.legs || 'stand'] || legsSet.stand;
  const layers = [];
  const back = S.back && S.back[f];
  const bo = (S.backAt && S.backAt[f]) || [0, 0];
  if (back) layers.push(L(back, bo[0] + bx + (o.backDx || 0), bo[1] + by + (o.backDy || 0)));
  if (o.weaponBehind && o.weapon) layers.push(L(o.weapon, 0, 0));
  layers.push(L(legPix, G.legX, G.legY + (o.legDy || 0)));
  layers.push(L(S.torso[f], S.torsoX[f] + bx, S.torsoY + by));
  if (o.offArm) layers.push(L(limbPix(G, o.offArm.sx + bx, o.offArm.sy + by, o.offArm.hx + bx, o.offArm.hy + by, S.limb), 0, 0));
  if (o.offWeapon) layers.push(L(o.offWeapon, 0, 0));
  const headLayer = L(S.head[f], S.headX[f] + hdx, S.headY + hdy);
  if (f === 'N') {
    if (o.arm) layers.push(L(limbPix(G, o.arm.sx + bx, o.arm.sy + by, o.arm.hx + bx, o.arm.hy + by, S.limb), 0, 0));
    if (o.smear) layers.push(L(o.smear, 0, 0));
    if (o.weapon && !o.weaponBehind) layers.push(L(o.weapon, 0, 0));
    layers.push(headLayer);
  } else {
    layers.push(headLayer);
    if (o.smear) layers.push(L(o.smear, 0, 0));
    if (o.arm) layers.push(L(limbPix(G, o.arm.sx + bx, o.arm.sy + by, o.arm.hx + bx, o.arm.hy + by, S.limb), 0, 0));
    if (o.weapon && !o.weaponBehind) layers.push(L(o.weapon, 0, 0));
  }
  for (const e of o.extra || []) layers.push(e);
  // THE INK LAST. Every part above arrived carrying its own outline, so before this pass the coat
  // was doubled down every join and missing wherever one part covered another's ring (the dark
  // warrior's sword arm, the war lord's cape edge). `houseOutline` peels the second coats, lays one
  // pixel of INK around whatever is still bare, and re-keys the whole silhouette against the
  // FIGURE's own normal — so the softening to '@' follows the man, not the part he is made of.
  return houseOutline(softenLit(compose(G.w, G.h, layers)), { key: '#', litKey: '@', lit: LIT });
}

// ------------------------------------------------------------------------------------ the rig
// Canonical rig points, expressed once on humanoid.js's 40x40 grid and mapped onto whichever
// canvas the species uses, so a war lord's shoulder sits exactly where a mercenary's would if he
// were that big. `rigDy` drops the whole rig for a short, deep-chested build (the dwarf).
const RIG40 = {
  S: { sh: [16, 15], offSh: [24, 15] },
  E: { sh: [21, 15], offSh: [18, 16] },
  N: { sh: [24, 15], offSh: [16, 15] },
};
const SWING40 = {
  S: [[16, 13, -62], [24, 23, 122], [25, 27, 143], [16, 23, -14]],
  E: [[21, 12, -56], [26, 22, 128], [27, 27, 147], [26, 22, 32]],
  N: [[25, 13, 54], [25, 11, 6], [17, 17, -82], [26, 22, 14]],
};
const STAB40 = {
  S: [[16, 19, -44], [21, 26, 26], [22, 27, 34], [15, 23, -16]],
  E: [[22, 19, 18], [29, 22, 88], [30, 22, 92], [26, 21, 50]],
  N: [[24, 20, -18], [26, 15, 8], [26, 14, 4], [26, 21, 16]],
};
const SMEAR40 = {
  S: { cx: 20, cy: 21, r0: 9, r1: 12, a0: -0.6, a1: 0.5 },
  E: { cx: 21, cy: 20, r0: 9, r1: 12, a0: -0.85, a1: 0.15 },
  N: { cx: 22, cy: 21, r0: 9, r1: 12, a0: -2.15, a1: -0.7 },
};

const shoulder = (S, f) => { const [x, y] = rigPt(S.G, ...RIG40[f].sh); return [x, y + (S.rigDy || 0)]; };
const offShoulder = (S, f) => { const [x, y] = rigPt(S.G, ...RIG40[f].offSh); return [x, y + (S.rigDy || 0)]; };
const armTo = (S, f, hx, hy, o = {}) => { const [sx, sy] = shoulder(S, f); return { sx: sx + (o.dsx || 0), sy: sy + (o.dsy || 0), hx, hy }; };
const offArmTo = (S, f, hx, hy) => { const [sx, sy] = offShoulder(S, f); return { sx, sy, hx, hy }; };
/** The swing/stab path for a species, in its own canvas coordinates. */
function pathFor(S, f) {
  const src = (S.style === 'stab' ? STAB40 : SWING40)[f];
  return src.map(([x, y, a]) => { const [px, py] = rigPt(S.G, x, y); return [px, py + (S.rigDy || 0), a]; });
}
function smearFor(S, f) {
  const m = SMEAR40[f], [cx, cy] = rigPt(S.G, m.cx, m.cy), k = S.G.k;
  return { cx, cy: cy + (S.rigDy || 0), r0: m.r0 * k, r1: m.r1 * k, a0: m.a0, a1: m.a1 };
}

/** Weapon pose at rest, per facing. */
function restWeapon(S, f, o = {}) {
  const r = S.rest[f];
  return S.weapon(f, { gx: r.gx + (o.dx || 0), gy: r.gy + (o.dy || 0), angle: r.a, len: r.len, glint: o.glint || 0 });
}
const restArm = (S, f, dx = 0, dy = 0) => armTo(S, f, S.rest[f].gx + dx, S.rest[f].gy + dy, S.off && S.off[f]);

// ------------------------------------------------------------------------------------ clips
function offHandLayers(S, f, o, dx = 0, dy = 0) {
  if (!S.offRest || !S.offRest[f]) return;
  const r = S.offRest[f];
  o.offArm = offArmTo(S, f, r.gx + dx, r.gy + dy);
  if (S.offWeapon) o.offWeapon = S.offWeapon(f, { gx: r.gx + dx, gy: r.gy + dy, angle: r.a, len: r.len });
}

function idleClip(S, f) {
  const mk = (dy, glint, phase) => {
    const o = { dy, legs: 'stand', arm: restArm(S, f, 0, dy), weapon: restWeapon(S, f, { dy, glint }) };
    offHandLayers(S, f, o, 0, dy);
    if (S.idleExtra) o.extra = S.idleExtra(f, phase, dy);
    return frame(S, f, o);
  };
  return { frames: [mk(0, 0, 0), mk(1, 0, 1), mk(1, 1, 2), mk(0, 0, 3)], durations: [340, 260, 220, 300], loop: true };
}

function walkClip(S, f) {
  const seq = f === 'E'
    ? [['c1', 0, 1, 0], ['c1', 1, 1, 1], ['p1', -1, 0, 0], ['c2', 0, -1, 0], ['c2', 1, -1, 1], ['p2', -1, 0, 0]]
    : [['lfwd', 0, 1, 0], ['lfwd', 1, 1, 1], ['pass', -1, 0, 0], ['rfwd', 0, -1, 0], ['rfwd', 1, -1, 1], ['pass', -1, 0, 0]];
  const frames = seq.map(([legs, dy, hx, hy], i) => {
    const o = { legs, dy, arm: restArm(S, f, hx, dy + hy), weapon: restWeapon(S, f, { dx: hx, dy: dy + hy }) };
    offHandLayers(S, f, o, -hx, dy + hy);
    if (S.idleExtra) o.extra = S.idleExtra(f, i % 4, dy, { sway: hx });
    return frame(S, f, o);
  });
  return { frames, durations: [95, 95, 95, 95, 95, 95], loop: true };
}

function attackClip(S, f) {
  const path = pathFor(S, f);
  const sm = smearFor(S, f);
  const lift = [1, -1, 0, 0], lunge = f === 'E' ? [-1, 3, 3, 1] : [0, 0, 0, 0];
  const legs = ['stand', f === 'E' ? 'c1' : 'lfwd', f === 'E' ? 'c1' : 'lfwd', 'stand'];
  const frames = path.map(([hx, hy, a], i) => {
    const len = S.rest[f].len + (i === 1 ? 1 : 0);
    const o = {
      dy: lift[i], dx: lunge[i], legs: legs[i],
      arm: armTo(S, f, hx, hy, S.off && S.off[f]),
      weapon: S.weapon(f, { gx: hx, gy: hy, angle: a, len }),
      weaponBehind: f === 'N' && i < 2,
    };
    if (i === 1) o.smear = smearArc(makePix(S.G.w, S.G.h), sm.cx, sm.cy, sm.r0, sm.r1, sm.a0, sm.a1, ['a', 'b', 'c', 'd']);
    offHandLayers(S, f, o, i === 1 || i === 2 ? -2 : 0, i === 0 ? -1 : 0);
    if (S.idleExtra) o.extra = S.idleExtra(f, i, lift[i], { sway: i === 1 ? 2 : 0 });
    return frame(S, f, o);
  });
  return { frames, durations: [115, 80, 110, 145], loop: false };
}

function hurtClip(S, f) {
  const lean = f === 'E' ? -2 : 0;
  const o = {
    dx: lean, dy: 1, hdx: lean, hdy: 1, legs: 'stand',
    arm: restArm(S, f, lean, 2), weapon: restWeapon(S, f, { dx: lean, dy: 2 }),
  };
  offHandLayers(S, f, o, lean + 1, 2);
  if (S.idleExtra) o.extra = S.idleExtra(f, 2, 1);
  const recoil = frame(S, f, o);
  return { frames: [solid(recoil, 'F'), recoil], durations: [70, 170], loop: false };
}

/** Facing-independent collapse toward the camera; the weapon falls out of the hand. */
function deathClip(S) {
  const G = S.G, k = G.k, r = S.rest.S;
  const P = (x, y) => rigPt(G, x, y);
  const drop = (gx, gy, a) => S.weapon('S', { gx, gy, angle: a, len: r.len });
  const mk = (o) => frame(S, 'S', { ...o, extra: [...(o.extra || []), ...(S.idleExtra ? S.idleExtra('S', 1, o.dy || 0) : [])] });
  const d = (n) => Math.round(n * k);
  const [h1x, h1y] = P(13, 24), [h2x, h2y] = P(12, 28), [h3x, h3y] = P(12, 32), [h4x, h4y] = P(12, 35);
  const [w1x, w1y] = P(15, 24), [w2x, w2y] = P(15, 29), [w3x, w3y] = P(16, 33), [w4x, w4y] = P(16, 35);
  const f1 = mk({ dy: d(1), hdx: -1, hdy: d(1), legs: 'stand', arm: armTo(S, 'S', h1x, h1y), weapon: drop(w1x, w1y, -34) });
  const f2 = mk({ dy: d(3), hdy: d(4), hdx: -1, legs: 'squat', arm: armTo(S, 'S', h2x, h2y, { dsy: d(3) }), weapon: drop(w2x, w2y, -66) });
  const f3 = mk({ dy: d(6), hdy: d(8), hdx: -1, legs: 'kneel', legDy: d(2), arm: armTo(S, 'S', h3x, h3y, { dsy: d(6) }), weapon: drop(w3x, w3y, -104) });
  const heap = compose(G.w, G.h, [
    L(mk({ dy: d(10), hdy: d(12), hdx: -2, legs: 'down', legDy: d(3), arm: armTo(S, 'S', h4x, h4y, { dsy: d(10) }) }), 0, 0),
    L(drop(w4x, w4y, -108), 0, 0),
  ]);
  const settle = compose(G.w, G.h, [
    L(mk({ dy: d(11), hdy: d(13), hdx: -2, legs: 'down', legDy: d(4), arm: armTo(S, 'S', h4x, h4y + 1, { dsy: d(11) }) }), 0, 0),
    L(drop(w4x, w4y + 1, -108), 0, 0),
  ]);
  return { frames: [f1, f2, f3, heap, settle], durations: [140, 170, 210, 620, 700], loop: false };
}

/** Build every clip of one species: name -> facing -> clip. West mirrors east. */
function buildSpecies(S) {
  const anims = {};
  const put = (name, f, a) => { (anims[name] ||= {})[f] = { name, facing: f, ...a }; };
  for (const f of ['S', 'E', 'N']) {
    put('idle', f, idleClip(S, f));
    put('walk', f, walkClip(S, f));
    put('attack', f, attackClip(S, f));
    put('hurt', f, hurtClip(S, f));
  }
  const d = deathClip(S);
  for (const f of ['S', 'E', 'N']) put('death', f, d);
  for (const name of Object.keys(anims)) {
    const e = anims[name].E;
    anims[name].W = { ...e, facing: 'W', frames: name === 'death' ? e.frames : e.frames.map((p) => mirrorLit(p, '')) };
  }
  return {
    anims, palette: S.palette, w: S.G.w, h: S.G.h, pivot: { x: S.G.px, y: S.G.py },
    emissive: 'YG', scale: 1,
  };
}

// ============================================================================ MERCENARY
// Deliberately the plain one — but plain is not the same as symmetrical. This is what a soldier
// looks like when nobody is paying for style: cropped hair under a sweatband, a buff jerkin cut
// into tabs at the hip, ONE strapped steel pauldron on the sword shoulder (the other was sold),
// a plain arming sword hanging point-down clear of his left leg, and a round BUCKLER held up on
// the off arm where it breaks the silhouette as a disc.
//
// The asymmetry IS the read: pauldron left, shield right, sword hanging below the shield. He is
// the only figure in the cast whose two sides do not match, and the only one showing bare legs
// below a short skirt — the swordsman is coated to the shin, the monk robed to the ankle, the
// dwarf mailed to the boot.
const MER_HEAD_S = body(`
....................
.......999999.......
......00999999......
......ggffffee......
......3WE22WE1......
......32222211......
......32222211......
.......322211.......
........2211........
.........221........
.........221........`);
const MER_HEAD_E = body(`
....................
.......999999.......
......00999999......
......ggffffee......
......32WE2211......
......32222211......
......32222211......
.......322211.......
........2211........
.........221........
.........221........`);
const MER_HEAD_N = body(`
....................
.......999999.......
......00999999......
......ggffffee......
......00999988......
......00999988......
.......099988.......
.......322211.......
........2211........
.........221........
.........221........`);
const MER_TORSO_S = keyed(`
.........555555.........
.........555555.........
..ccbba555555555555.....
.ccbbba555555555555.....
.ccbbba555555555555.....
..ccbba555555555555.....
.....55559955555555.....
.....55559955555555.....
.....55555995555555.....
.....55555995555555.....
.....88999999999999.....
.....889999gg999999.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555.5555.555.....
......555...55..55......`, '7456', { gain: 0.58, mid: 0.52, up: 0.52, local: 0.32 });
const MER_TORSO_E = keyed(`
..........555555........
..........555555........
...ccbba555555555555....
..ccbbba555555555555....
..ccbbba555555555555....
...ccbba555555555555....
......55559955555555....
......55559955555555....
......55555995555555....
......55555995555555....
......88999999999999....
......889999gg999999....
......55555555555555....
......55555555555555....
......55555555555555....
......55555555555555....
......55555.5555.555....
.......555...55..55.....`, '7456', { gain: 0.58, mid: 0.52, up: 0.52, local: 0.32 });
const MER_TORSO_N = keyed(`
.........555555.........
.........555555.........
..ccbba555555555555.....
.ccbbba555555555555.....
.ccbbba555555555555.....
..ccbba555555555555.....
.....55559955555555.....
.....55559955555555.....
.....55555995555555.....
.....55555995555555.....
.....88999999999999.....
.....889999gg999999.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555.5555.555.....
......555...55..55......`, '7456', { gain: 0.58, mid: 0.52, up: 0.52, local: 0.32 });

const MERCENARY = {
  G: MAN,
  palette: humanPalette({ skin: '#c99a6e', cloth: '#57683f', leather: '#5c3d24', metal: '#949aa6', accent: '#6b4f2e', eye: '#e8f0ff' }),
  legs: { S: LEGS_S, E: LEGS_E },
  head: { S: MER_HEAD_S, E: MER_HEAD_E, N: MER_HEAD_N }, headX: { S: 14, E: 14, N: 14 }, headY: 6,
  torso: { S: MER_TORSO_S, E: MER_TORSO_E, N: MER_TORSO_N }, torsoX: { S: 12, E: 12, N: 12 }, torsoY: 16,
  limb: { lit: '2', dark: '1', fist: '2', fistLit: '3' },
  style: 'swing',
  // the sword hangs OUTSIDE his own leg, point down; the buckler rides at chest height where a
  // shield actually blocks, and sticks five pixels past his ribs
  // the grip rides two rows higher than it used to: hung any lower the point of the sword was the
  // lowest pixel of the sprite, so his CONTACT ROW was a sword tip and it bobbed with his breathing
  rest: { S: { gx: 13, gy: 28, a: 186, len: 12 }, E: { gx: 34, gy: 28, a: 174, len: 12 }, N: { gx: 34, gy: 28, a: 174, len: 12 } },
  offRest: { S: { gx: 33, gy: 26 }, E: { gx: 16, gy: 27 }, N: { gx: 14, gy: 26 } },
  weapon: (f, o) => bladePix(MAN, o.gx, o.gy, o.angle, { len: o.len, w0: 0.9, w1: 0.6, glint: o.glint || 0, guard: 2, grip: '9', pommel: 'e' }),
  offWeapon: (f, o) => bucklerPix(MAN, o.gx, o.gy, 5, { aspect: 0.86 }),
};

// ============================================================================ SWORDSMAN
// The duellist, and the only LONG COAT in the cast. Every decision here serves one shape: a
// narrow upright column that BELLS OUT below the belt into a heavy skirted coat whose hem arches
// up over the boots and hangs in two points at the sides — and, clear of that bell on the left,
// the long slim blade held LOW, point to the floor, a straight diagonal with air on both sides.
//
// He used to be "a blue noodle with a stick": a tube of one blue with the sword drawn INSIDE his
// own outline, where a silhouette test cannot see it, and a head the same ball as the mercenary's.
// Nothing about the read now depends on colour:
//   COLLAR  two standing points flank the jaw, so the head is pinched instead of set on a tube
//   COAT    14 px at the belt, 22 px at the hem, and then SPLIT — the skirt parts into two panels
//           that taper to points with the boots walking out of the gap between them. That split is
//           what finally tells him apart from the Monk, who was the other bell in the rank.
//   FRONT   a leather-faced placket down the centre with three brass buttons beside it, drawn in
//           the leather and accent vocabularies because `keyed()` re-keys anything typed in cloth
//   BLADE   outside the silhouette from grip to point, at the low guard
// The cloth is drawn as flat shape and re-lit by `keyed()` (pixelPainter.keyShade) off the house
// top-left terminator, which is why a 22-px-wide coat turns instead of pillowing.
const SWD_HEAD_S = body(`
....................
.......888888.......
......89999998......
.....0999999988.....
.....0222222118.....
.....0322222118.....
.....03WE22WE18.....
.....0322211118.....
......32222118......
.......322211.......
....54..2211..47....
...5544.2211.4477...
...55555555555444...
..5555555555555444..`);
const SWD_HEAD_E = body(`
....................
.......888888.......
......89999998......
.....0999999988.....
.....0922222211.....
.....0922222211.....
.....0922WE2211.....
.....0922221111.....
......92222111......
.......922211.......
....54..2211..47....
...5544.2211.4477...
...55555555555444...
..5555555555555444..`);
const SWD_HEAD_N = body(`
....................
.......888888.......
......89999998......
.....0999999988.....
.....0999999988.....
.....0999999988.....
.....0999999988.....
.....0999999988.....
......99999988......
.......999988.......
....54..2211..47....
...5544.2211.4477...
...55555555555444...
..5555555555555444..`);
// The coat. Its ROWS ARE THE SILHOUETTE: shoulders 16 px, chest 14, belt 14, and then the bell —
// 16, 18, 20, 22 — with the hem arched up in the middle so the boots walk out from under it
// instead of the coat ending on one flat ruled line. Drawn flat and re-lit by `keyed()`.
const SWD_TORSO_S = keyed(`
........................
.....55555555555555.....
....5555555985555555....
....5555555985555555....
.....5555g598555555.....
.....55555598555555.....
.....5555g598555555.....
.....55555598555555.....
.....5555g598555555.....
.....55555598555555.....
.....88999999999999.....
.....889999gg999999.....
.....55555555555555.....
.....55555555555555.....
....5555555555555555....
....5555555555555555....
...555555555555555555...
...55555555..55555555...
..555555555..555555555..
..55555555....55555555..
.555555555....555555555.
.55555555......55555555.
.555555..........555555.`, '7456', { gain: 0.50, mid: 0.56, up: 0.5, local: 0.28 });
const SWD_TORSO_E = keyed(`
........................
......555555555555......
.....55555559855555.....
.....55555559855555.....
......5555g5985555......
......555555985555......
......5555g5985555......
......555555985555......
......5555g5985555......
......555555985555......
......889999999999......
......889999gg9999......
......555555555555......
......555555555555......
.....55555555555555.....
.....55555555555555.....
....5555555..5555555....
...55555555..55555555...
..55555555....55555555..
..55555555....55555555..
..5555555......5555555..
..555555........555555..`, '7456', { gain: 0.50, mid: 0.56, up: 0.5, local: 0.28 });
const SWD_TORSO_N = keyed(`
........................
.....55555555555555.....
....5555555555555555....
....5555555555555555....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....88999999999999.....
.....889999gg999999.....
.....55555555555555.....
.....55555555555555.....
....5555555555555555....
....5555555555555555....
...555555555555555555...
...55555555..55555555...
..555555555..555555555..
..55555555....55555555..
.555555555....555555555.
.55555555......55555555.
.555555..........555555.`, '7456', { gain: 0.50, mid: 0.56, up: 0.5, local: 0.28 });

const SWORDSMAN = {
  G: MAN,
  palette: humanPalette({ skin: '#d8ab80', cloth: '#3f5a7e', leather: '#6b5138', metal: '#aab2c0', accent: '#a8742c', eye: '#dff2ff' }),
  legs: { S: LEGS_S, E: LEGS_E },
  head: { S: SWD_HEAD_S, E: SWD_HEAD_E, N: SWD_HEAD_N }, headX: { S: 14, E: 14, N: 14 }, headY: 5,
  torso: { S: SWD_TORSO_S, E: SWD_TORSO_E, N: SWD_TORSO_N }, torsoX: { S: 12, E: 12, N: 12 }, torsoY: 17,
  // a coat sleeve, not a bare arm: one step LIGHTER than the coat it lies on and edged in the step
  // below, so it separates without the house ink cutting a black line across his own chest
  limb: { lit: '6', dark: '5', fist: '2', fistLit: '3', edge: '4' },
  style: 'stab',
  // THE LOW GUARD. The grip sits OUTSIDE the coat and the point falls toward the floor, so the
  // blade is a line of its own in the silhouette instead of a stripe painted down the chest.
  rest: { S: { gx: 13, gy: 27, a: -150, len: 15 }, E: { gx: 34, gy: 27, a: 148, len: 15 }, N: { gx: 34, gy: 27, a: 150, len: 15 } },
  offRest: { S: { gx: 33, gy: 26 }, E: { gx: 14, gy: 27 }, N: { gx: 14, gy: 26 } },
  weapon: (f, o) => bladePix(MAN, o.gx, o.gy, o.angle, { len: o.len, w0: 0.6, w1: 0.4, glint: o.glint || 0, guard: 3, grip: '8', pommel: 'g' }),
};

// ============================================================================ MONK
// The calm one, and the only figure in the cast with a NECK. Everything else here wears armour or
// a collar that runs the head straight into the shoulders; the monk's shaved skull sits on three
// pixels of bare throat, and that notch is half his read. The other half is the QUARTERSTAFF —
// a dead-straight vertical planted on the floor and rising past the top of his head, held three
// columns clear of the robe so that a column of air survives the ink pass and the staff stays a
// line of its own in the silhouette instead of a stripe painted on his chest.
//
// He used to be "an unreadable brown blob": a 22-px-wide robe ending on one flat ruled hem, the
// staff drawn inside his own outline and a head that merged into the shoulders. Now:
//   NARROW    8 px at the shoulder, 12 through the body, 16 at the hem — the slimmest human here
//   UNCUT     nothing strapped, buckled, spiked or pauldroned; one rope belt and one STOLE, a
//             three-pixel rust band falling from the left shoulder to the right hip — the only
//             thing on him that is not undyed hemp, and drawn in the accent keys so the robe's
//             own terminator cannot re-key it away
//   TURNS     his cloth takes four ADJACENT steps of the house ramp (picks [1,3,4,5]) under a
//             gentle terminator: the old [0,2,4,6] slice spanned 0.14-0.83 in value, which split
//             the robe into a white half and a brown half and read as two garments
//   BAREFOOT  no boot cuff, no sole: `barefoot()` repaints the shared leg block as skin and
//             shaves the boot's overhang off, so the last rows are a foot and not a shoe
//   PLANTED   the staff's ferrule is pinned to the pivot row (`down = py - gy`), so the one thing
//             an idle may never move — the row he stands on — does not move when he breathes
//   HEM       three lobes and two low points, never a straight line
const MNK_HEAD_S = body(`
....................
........2222........
.......322222.......
......32222211......
......32222211......
.....2322222111.....
.....23WE22WE11.....
......32211211......
.......322211.......
........2211........
.........221........
.........221........
.........221........`);
const MNK_HEAD_E = body(`
....................
........2222........
.......322222.......
......32222211......
......32222211......
.....2322222111.....
.....2322EE2111.....
......32222111......
.......322211.......
........2211........
.........221........
.........221........
.........221........`);
const MNK_HEAD_N = body(`
....................
........2222........
.......322222.......
......32222211......
......32222211......
.....2322222111.....
.....2322222111.....
......32222211......
.......322211.......
........2211........
.........221........
.........221........
.........221........`);
const MNK_TORSO_S = keyed(`
........................
........55555555........
......gfe555555555......
......gfe555555555......
......5gfe55555555......
......55gfe5555555......
......555gfe555555......
......5555gfe55555......
......55555gfe5555......
......555555gfe555......
......ggffffffffff......
......555555555555......
......555555555555......
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
....5555555555555555....
....5555555555555555....
....5555555555555555....
....5555555555555555....
....5555555555555555....
....5555555555555555....
....55555.5555.55555....
.....555........555.....`, '7456', { gain: 0.48, mid: 0.60, up: 0.46, local: 0.26 });
const MNK_TORSO_E = keyed(`
........................
.........55555555.......
.......gfe555555555.....
.......gfe555555555.....
.......5gfe55555555.....
.......55gfe5555555.....
.......555gfe555555.....
.......5555gfe55555.....
.......55555gfe5555.....
.......555555gfe555.....
.......ggffffffffff.....
.......555555555555.....
.......555555555555.....
......55555555555555....
......55555555555555....
......55555555555555....
......55555555555555....
.....5555555555555555...
.....5555555555555555...
.....5555555555555555...
.....5555555555555555...
.....5555555555555555...
.....5555555555555555...
.....55555.5555.55555...
......555........555....`, '7456', { gain: 0.48, mid: 0.60, up: 0.46, local: 0.26 });
const MNK_TORSO_N = keyed(`
........................
........55555555........
......555555555gfe......
......555555555gfe......
......55555555gfe5......
......5555555gfe55......
......555555gfe555......
......55555gfe5555......
......5555gfe55555......
......555gfe555555......
......ggffffffffff......
......555555555555......
......555555555555......
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
....5555555555555555....
....5555555555555555....
....5555555555555555....
....5555555555555555....
....5555555555555555....
....5555555555555555....
....55555.5555.55555....
.....555........555.....`, '7456', { gain: 0.48, mid: 0.60, up: 0.46, local: 0.26 });

/**
 * Bare feet under the robe. The shared boot block is repainted skin (`BAREFOOT`) and then SHAVED:
 * the outermost fill pixel of every run in the bottom four rows comes off, which takes the cuff
 * and the sole overhang away and leaves a narrow foot. A recolour on its own left the monk in
 * flesh-coloured BOOTS, which is worse than leaving them brown.
 */
const BAREFOOT = { 7: '1', 8: '1', 9: '2', 0: '3', s: '1' };
function shaveBoot(p, rows = 4) {
  const o = clone(p);
  for (let y = p.h - rows; y < p.h; y++) {
    for (let x = 0; x < p.w; x++) {
      if (!p.d[y * p.w + x]) continue;
      let x1 = x; while (x1 + 1 < p.w && p.d[y * p.w + x1 + 1]) x1++;
      if (x1 - x >= 4) { o.d[y * p.w + x] = 0; o.d[y * p.w + x1] = 0; }
      x = x1;
    }
  }
  return o;
}
const barefoot = (set) => Object.fromEntries(Object.entries(set).map(([k, p]) => [k, shaveBoot(recolor(p, BAREFOOT))]));

const MONK = {
  G: MAN,
  // his robe takes one step higher off the house ramp than the armoured five: undyed hemp in
  // torchlight is the lightest cloth in the cast, and it is what keeps his value spread open
  palette: humanPalette({ skin: '#c99a72', cloth: '#8a7247', leather: '#6a5030', metal: '#9aa0a8', accent: '#9c5b36', eye: '#f0e4c8', picks: { cloth: [1, 3, 4, 5] } }),
  legs: { S: barefoot(LEGS_S), E: barefoot(LEGS_E) },
  head: { S: MNK_HEAD_S, E: MNK_HEAD_E, N: MNK_HEAD_N }, headX: { S: 14, E: 14, N: 14 }, headY: 6,
  torso: { S: MNK_TORSO_S, E: MNK_TORSO_E, N: MNK_TORSO_N }, torsoX: { S: 12, E: 12, N: 12 }, torsoY: 17,
  // a sleeve, not a bare arm: the robe covers him to the wrist and only the fist is skin
  // the sleeve is one step LIGHTER than the robe it lies on and edged in the step below it, so the
  // arm reads as cloth on cloth instead of as a stick of house ink scratched across his chest
  limb: { lit: '6', dark: '5', fist: '2', fistLit: '3', edge: '4' },
  style: 'stab',
  // THE STAFF STANDS ON THE FLOOR. `staffPix` puts 66% of its length above the grip and 34% below,
  // so a grip on row 31 with len 41 plants the ferrule on the pivot row and lifts the head of the
  // staff two rows above his skull — the tallest thing about him, and none of it touching cloth.
  rest: { S: { gx: 14, gy: 26, a: 0, len: 39 }, E: { gx: 34, gy: 26, a: 0, len: 39 }, N: { gx: 34, gy: 26, a: 0, len: 39 } },
  // the off hand rests open at the chest — the one calm gesture in a room full of raised weapons
  offRest: { S: { gx: 31, gy: 27 }, E: { gx: 15, gy: 27 }, N: { gx: 14, gy: 27 } },
  weapon: (f, o) => staffPix(MAN, o.gx, o.gy, o.angle, {
    len: o.len, glint: o.glint || 0,
    // upright: the foot of the staff is nailed to the pivot row whatever the grip does
    ...(o.angle === 0 ? { down: MAN.py - o.gy, up: o.len - (MAN.py - o.gy) } : {}),
  }),
};

// ============================================================================ DARK WARRIOR
// Black plate with no skin anywhere on it — the point is that you cannot tell what is inside. He
// is the TALL HORNED one, and three things carry that from across a room, none of them colour:
//   HORNS      two of them, one pixel at the tip and three at the root, sweeping up and OUT from
//              the temples of a closed sallet, so the top of his silhouette is a V and nobody
//              else's is. They are drawn in the LEATHER keys, not the plate ramp — horn is a
//              different material, and (see below) anything typed in the plate's own keys would
//              have been re-lit into a pair of pale antlers by the helm's terminator.
//   PAULDRONS  spiked, and WIDER THAN HIS OWN STANCE, over a chest that narrows all the way to the
//              belt: the torso is a wedge standing on a waist
//   CLOAK      hung behind him from the gorget to the floor, widening as it falls, so the wedge
//              stands on a triangle instead of on two boots
// The closed visor is two slits with an ember behind them (`Y`, the sheet's emissive key). He was a
// dark blob with the sword painted inside his own outline; the blade now leaves the silhouette at
// the hip and crosses empty air past his shoulder.
//
// HE IS THE ONE FIGURE HAND-VALUED, not `keyed()`. A suit of plate is all structure — gorget,
// pauldron, breastplate, tasset — and a flat block re-lit by one terminator turns that structure
// into abstract diagonal bands across the chest. Here the ramp runs LEFT TO RIGHT across the form
// (`c` lit, `b` body, `a` shadow, exactly the top-left key light) and every top-left facing edge
// carries one pixel of `d`: that rim is what a near-black creature has instead of a highlight, and
// without it his whole value range collapses to 0.31 and style.js starts warning.
const DKW_HEAD_S = body(`
....................
.9................8.
.99..............88.
..99............88..
..999..........888..
...999........888...
...999ddccbbaa888...
.....ddcccbbbaa.....
....ddccccbbbbaa....
....dcccccbbbbaa....
....dYYcbbbbYYba....
....dcbbbbbbbbaa....
....dcbbbbbbbaaa....
.....cbbbbbbaaa.....
.....cbbbbbaaaa.....
......cbbaaaaa......`);
const DKW_HEAD_E = body(`
....................
.9................8.
.99..............88.
..99............88..
..999..........888..
...999........888...
...999ddccbbaa888...
.....ddcccbbbaa.....
....ddccccbbbbaa....
....dcccccbbbbaa....
....dYYcbbbbbbba....
....dcbbbbbbbbaa....
....dcbbbbbbbaaa....
.....cbbbbbbaaa.....
.....cbbbbbaaaa.....
......cbbaaaaa......`);
const DKW_HEAD_N = body(`
....................
.9................8.
.99..............88.
..99............88..
..999..........888..
...999........888...
...999ddccbbaa888...
.....ddcccbbbaa.....
....ddccccbbbbaa....
....dcccccbbbbaa....
....dcbbbbbbbbaa....
....dcbbbbbbbbaa....
....dcbbbbbbbaaa....
.....cbbbbbbaaa.....
.....cbbbbbaaaa.....
......cbbaaaaa......`);
const DKW_TORSO_S = body(`
........................
........dcbbbbaa........
.......dccbbbbbaa.......
.......dcbbbbbbaa.......
...dc.dccbbbbbbbaa.ba...
..ddcccbbbbbbbbbbbaaaa..
..ddccbbbbbbbbbbbbaaaa..
...dcbbbbbbbbbbbbbaaa...
....dccbbbcdbbbbaaaa....
.....dcbbbcdbbbaaaa.....
.....dcbbbcdbbbaaaa.....
.....88999999999999.....
.....889999ee999999.....
....dccbbbbbbbbbaaaa....
....dcbbbbbbbbbbaaaa....
....dcbbbbbbbbbbaaaa....
.....dcbbbbbbbaaaaa.....
.....dcbbbbbbaaaaaa.....
......dcbbbbbaaaaa......
.......dcbbbaaaaa.......`);
const DKW_TORSO_E = body(`
........................
........dcbbbbaa........
.......dccbbbbbaa.......
.......dcbbbbbbaa.......
...dc.dccbbbbbbbaa.ba...
..ddcccbbbbbbbbbbbaaaa..
..ddccbbbbbbbbbbbbaaaa..
...dcbbbbbbbbbbbbbaaa...
....dccbbbcdbbbbaaaa....
.....dcbbbcdbbbaaaa.....
.....dcbbbcdbbbaaaa.....
.....88999999999999.....
.....889999ee999999.....
....dccbbbbbbbbbaaaa....
....dcbbbbbbbbbbaaaa....
....dcbbbbbbbbbbaaaa....
.....dcbbbbbbbaaaaa.....
.....dcbbbbbbaaaaaa.....
......dcbbbbbaaaaa......
.......dcbbbaaaaa.......`);
const DKW_TORSO_N = body(`
........................
........dcbbbbaa........
.......dccbbbbbaa.......
.......dcbbbbbbaa.......
...dc.dccbbbbbbbaa.ba...
..ddcccbbbbbbbbbbbaaaa..
..ddccbbbbbbbbbbbbaaaa..
...dcbbbbbbbbbbbbbaaa...
....dccbbbcdbbbbaaaa....
.....dcbbbcdbbbaaaa.....
.....dcbbbcdbbbaaaa.....
.....88999999999999.....
.....889999ee999999.....
....dccbbbbbbbbbaaaa....
....dcbbbbbbbbbbaaaa....
....dcbbbbbbbbbbaaaa....
.....dcbbbbbbbaaaaa.....
.....dcbbbbbbaaaaaa.....
......dcbbbbbaaaaa......
.......dcbbbaaaaa.......`);
/** His cloak: a fall of the same near-black cloth from the gorget to the floor, drawn behind. */
// hung one row higher than the boots: an idle may move anything above the belt, and the one thing
// it may never move is the row the figure stands on — a cloak hem at the pivot row breathes with him
const DKW_CAPE = capePix(MAN, 24, 19, { w: 10, h: 25 });
const DKW_CAPE_N = capePix(MAN, 24, 19, { w: 10, h: 24, back: true });

const DARK_WARRIOR = {
  G: MAN,
  palette: humanPalette({ skin: '#5f5a70', cloth: '#33374c', leather: '#3c3448', metal: '#3b4054', accent: '#8e2f34', eye: '#ff5a3a', picks: { metal: [0, 2, 3, 5] } }),
  legs: { S: LEGS_S_PLATE, E: LEGS_E_PLATE },
  head: { S: DKW_HEAD_S, E: DKW_HEAD_E, N: DKW_HEAD_N }, headX: { S: 14, E: 14, N: 14 }, headY: 2,
  torso: { S: DKW_TORSO_S, E: DKW_TORSO_E, N: DKW_TORSO_N }, torsoX: { S: 12, E: 12, N: 12 }, torsoY: 16,
  back: { S: DKW_CAPE, E: DKW_CAPE, N: null }, backAt: { S: [0, 0], E: [-2, 0], N: [0, 0] },
  // plate on plate: edged in the bottom of its own ramp, never in house ink — a black-and-lilac
  // outline ring laid down the middle of a breastplate reads as a crack, not as an arm
  limb: { lit: 'b', dark: 'a', fist: 'b', fistLit: 'c', edge: 'a' },
  style: 'swing',
  // the blade leaves the body at the hip and crosses air past the shoulder: a line, not a stripe
  rest: { S: { gx: 16, gy: 32, a: -34, len: 13 }, E: { gx: 33, gy: 31, a: 34, len: 13 }, N: { gx: 33, gy: 32, a: 30, len: 13 } },
  weapon: (f, o) => bladePix(MAN, o.gx, o.gy, o.angle, { len: o.len, w0: 1.0, w1: 0.7, glint: o.glint || 0, guard: 2, grip: '8', pommel: 'e' }),
  // seen from behind the cloak IS the silhouette, so it is drawn over him instead of behind
  idleExtra: (f, phase, dy) => (f === 'N' ? [L(DKW_CAPE_N, 0, dy)] : []),
};

// ============================================================================ DWARVEN GUARD
// THREE TIERS, and no man in the game has them: a war helm 20 px across, a forked beard 18 px
// across, and a body of 14. The beard overhangs his chest by two and forks into two points over
// the belt. Read from the top down the outline goes WIDE, WIDE, NARROW — which is a dwarf, and is
// not a shape any human silhouette in this file can make.
//
// THE HELM IS A HELM, NOT A HAT. It used to be a 4-px dome sitting on a flat 23-px disc of near
// white — a sombrero, and the brightest thing in a rank that ends with a War Lord in polished
// plate. What replaced it is armour: a ROUNDED skull that widens fast and then goes vertical (4,
// 8, 10, 12, 12, 12 px), a brow band, a 20-px brim two rows deep whose ends turn DOWN into cheek
// plates flanking the beard, and a nasal bar down the middle. Nothing under it but two
// catch-lights in the shadow of the brim.
//
// The hauberk is a long surcoat cut into tabs at the hem, so almost no leg shows; the weight is
// all in the top half. The BEARDED AXE hangs on his off side, its single crescent half his height.
const DWG_HEAD_S = body(`
..........ccba..........
........bcddccba........
.......bccddccbba.......
......bbccddcccbba......
......bbcccccccbba......
......bbcccccccbba......
....bbccccccccccbbaa....
...bbbbbbbbbbbbbbaaaa...
...bbaa111aaaa111aaaa...
...aa.11W11aa11W11.aa...
...aa.ggffffffffee.aa...
....gggfffeeeefffeee....
...ffffeeeeffeeeeeeee...
...fffeeeeeeeeeeeeeee...
....ffeeeeeeeeeeeeee....
....ffeeee....eeeeee....
.....feee......eeee.....`);
const DWG_HEAD_E = body(`
..........ccba..........
........bcddccba........
.......bccddccbba.......
......bbccddcccbba......
......bbcccccccbba......
......bbcccccccbba......
....bbccccccccccbbaa....
...bbbbbbbbbbbbbbaaaa...
...bbaa111aaaa111aaaa...
...aa.11W11aa11111.aa...
...aa.ggffffffffee.aa...
....gggfffeeeefffeee....
...ffffeeeeffeeeeeeee...
...fffeeeeeeeeeeeeeee...
....ffeeeeeeeeeeeeee....
....ffeeee....eeeeee....
.....feee......eeee.....`);
const DWG_HEAD_N = body(`
..........ccba..........
........bcddccba........
.......bccddccbba.......
......bbccddcccbba......
......bbcccccccbba......
......bbcccccccbba......
....bbccccccccccbbaa....
...bbbbbbbbbbbbbbaaaa...
...bbaaaaaaaaaaaaaaaa...
...aa.ggffffffffee.aa...
...aa.ggffffffffee.aa...
....gggfffeeeefffeee....
...ffffeeeeffeeeeeeee...
...fffeeeeeeeeeeeeeee...
....ffeeeeeeeeeeeeee....
....ffeeee....eeeeee....
.....feee......eeee.....`);
const DWG_TORSO_S = keyed(`
........................
......555555555555......
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....88999999999999.....
.....889999gg999999.....
.....55555555555555.....
.....55555555555555.....
....5555555555555555....
....5555555555555555....
....5555555555555555....
....5555555555555555....
....5555555555555555....
....55555.5555.55555....
.....555...55...555.....`, '7456', { gain: 0.56, mid: 0.50, up: 0.5, local: 0.3 });
const DWG_TORSO_E = keyed(`
........................
.......555555555555.....
......55555555555555....
......55555555555555....
......55555555555555....
......55555555555555....
......55555555555555....
......55555555555555....
......55555555555555....
......88999999999999....
......889999gg999999....
......55555555555555....
......55555555555555....
.....5555555555555555...
.....5555555555555555...
.....5555555555555555...
.....5555555555555555...
.....5555555555555555...
.....55555.5555.55555...
......555...55...555....`, '7456', { gain: 0.56, mid: 0.50, up: 0.5, local: 0.3 });
const DWG_TORSO_N = keyed(`
........................
......555555555555......
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....55555555555555.....
.....88999999999999.....
.....889999gg999999.....
.....55555555555555.....
.....55555555555555.....
....5555555555555555....
....5555555555555555....
....5555555555555555....
....5555555555555555....
....5555555555555555....
....55555.5555.55555....
.....555...55...555.....`, '7456', { gain: 0.56, mid: 0.50, up: 0.5, local: 0.3 });

const DWARVEN_GUARD = {
  G: MAN,
  palette: humanPalette({ skin: '#c08b62', cloth: '#7c3330', leather: '#5b3f28', metal: '#8f96a2', accent: '#a8722e', eye: '#ffe6b0', picks: { metal: [1, 3, 5, 6] } }),
  legs: { S: LEGS_S, E: LEGS_E },
  head: { S: DWG_HEAD_S, E: DWG_HEAD_E, N: DWG_HEAD_N }, headX: { S: 12, E: 12, N: 12 }, headY: 11,
  torso: { S: DWG_TORSO_S, E: DWG_TORSO_E, N: DWG_TORSO_N }, torsoX: { S: 12, E: 12, N: 12 }, torsoY: 18,
  limb: { lit: '2', dark: '1', fist: '2', fistLit: '3' },
  rigDy: 5,
  style: 'swing',
  rest: { S: { gx: 15, gy: 35, a: -30, len: 12 }, E: { gx: 33, gy: 35, a: 32, len: 12 }, N: { gx: 33, gy: 35, a: 28, len: 12 } },
  weapon: (f, o) => beardAxePix(MAN, o.gx, o.gy, o.angle, { len: o.len, head: 8, glint: o.glint || 0, side: f === 'N' ? 1 : -1 }),
};

// ============================================================================ WAR LORD
// The boss of the human family and the deepest human threat in the dungeon. He is drawn on a
// canvas half again as big as everyone else's — 64x72 against 48x48 — so that his 66-px figure
// lands at the SAME texel size as the mercenary's 39-px one instead of being a blown-up copy of a
// smaller man. Four things carry the read, in this order, from across a lit room:
//   1. a tall bladed CREST standing over the helm, taller than a man's head is deep
//   2. PAULDRONS wider than his own stance, with gold on the brow band and the gorget
//   3. a crimson CAPE falling behind him all the way to the floor
//   4. a two-handed GREATSWORD rising across his body past his own shoulder
const WLD_HEAD_S = body(`
............................
.............65.............
............6554............
...........655444...........
...........655444...........
..........65554444..........
..........65554444..........
..........65554444..........
...........655444...........
...........655444...........
............gffe............
.........bccddddccb.........
........bccddddddccb........
.......abbccddddccbba.......
.......abbccddddccbba.......
......ggffffffffffffee......
......aabbYYaaaaYYbbaa......
......aabbYYaaaaYYbbaa......
......abbccccccccccbaa......
......abbccccccccccbaa......
.......abbccccccccbaa.......
.......abbccccccccbaa.......
........abbccccccbaa........
.........abbccccbaa.........`);
const WLD_HEAD_E = body(`
............................
...........65...............
..........6554..............
.........655444.............
.........655444.............
........65554444............
........65554444............
........65554444............
.........655444.............
.........655444.............
..........gffe..............
........bccddddccb..........
.......bccddddddccb.........
......abbccddddccbba........
......abbccddddccbba........
.....ggffffffffffffee.......
.....aabbYYaaaabbbbaa.......
.....aabbYYaaaabbbbaa.......
.....abbccccccccccccbaa.....
.....abbccccccccccccbaa.....
......abbccccccccccbaa......
......abbccccccccccbaa......
.......abbccccccccbaa.......
........abbccccccbaa........`);
const WLD_HEAD_N = body(`
............................
.............65.............
............6554............
...........655444...........
...........655444...........
..........65554444..........
..........65554444..........
..........65554444..........
...........655444...........
...........655444...........
............gffe............
.........bccddddccb.........
........bccddddddccb........
.......abbccddddccbba.......
.......abbccddddccbba.......
......ggffffffffffffee......
......abbccccccccccbaa......
......abbccccccccccbaa......
......abbccccccccccbaa......
......abbccccccccccbaa......
.......abbccccccccbaa.......
.......abbccccccccbaa.......
........abbccccccbaa........
.........abbccccbaa.........`);
const WLD_TORSO_S = body(`
..................................
..........ggffffffffffee..........
.......aabbccccccccccccbbaa.......
...abbccddddccbbbbbbbbccddddccb...
.aabbccdddddccbbbbbbccdddddccbbaa.
.aabbccdddddccbbbbbbccdddddccbbaa.
.aabbccdddddccbggggbbccdddddccbba.
..abbccddddccbggffbbccddddccbbaa..
...abbccdddccbggffbbccdddccbbaa...
....abbccddccbggffbbccddccbbaa....
.....abbcccccbggffbbcccccbbaa.....
......abbcccccbggbbcccccbbaa......
......abbcccccbggbbcccccbbaa......
......abbccccccbbcccccccbbaa......
......abbccccccbbcccccccbbaa......
......abbbccccbbbccccccbbbaa......
.....8899999ggggggg9999998888.....
.....889999999ffff99999998888.....
......aabbcccccccccccccbbbaa......
......aabbcccccccccccccbbbaa......
......aabbccccbbbbccccccbbaa......
......aabbcccbbbbbbcccccbbaa......
.....aabbcccbbbbbbbbcccccbbaa.....
.....aabbcccbbbbbbbbcccccbbaa.....
.....aabbccbbbbbbbbbbccccbbaa.....
.....aabbccbbbbbbbbbbccccbbaa.....
.....aabbccbbbbbbbbbbccccbbaa.....
......aabbbbbbbbbbbbbbbbbbaa......
......aabbbbbbbbbbbbbbbbbbaa......
.......aaaaaaaaaaaaaaaaaaaa.......
..................................
..................................`);
const WLD_TORSO_E = body(`
..................................
.........ggffffffffffee...........
......aabbccccccccccccbbaa........
.....abbccddddccbbbbbbccddddccb...
....aabbccdddddccbbbbccdddddccbba.
....aabbccdddddccbbbbccdddddccbba.
....aabbccdddddccbggbbccdddddccba.
.....abbccddddccbggffbccddddccbba.
......abbccdddccbggffbccdddccbbaa.
.......abbccddcbggffbbccddccbbaa..
........abbcccbggffbbcccccbbaa....
........abbccccbggbbcccccbbaa.....
........abbccccbggbbcccccbbaa.....
........abbcccccbbcccccccbbaa.....
........abbcccccbbcccccccbbaa.....
........abbbcccbbbccccccbbbaa.....
.......8899999ggggggg99999888.....
.......889999999ffff9999988888....
........aabbccccccccccccbbbaa.....
........aabbccccccccccccbbbaa.....
........aabbccccbbbbccccccbbaa....
........aabbcccbbbbbbcccccbbaa....
.......aabbcccbbbbbbbbcccccbbaa...
.......aabbcccbbbbbbbbcccccbbaa...
.......aabbccbbbbbbbbbbccccbbaa...
.......aabbccbbbbbbbbbbccccbbaa...
.......aabbccbbbbbbbbbbccccbbaa...
........aabbbbbbbbbbbbbbbbbbaa....
........aabbbbbbbbbbbbbbbbbbaa....
.........aaaaaaaaaaaaaaaaaaaa.....
..................................
..................................`);
const WLD_CAPE_S = capePix(LORD, 32, 31, { w: 18, h: 34 });
const WLD_CAPE_N = capePix(LORD, 32, 33, { w: 15, h: 31, back: true });

const WAR_LORD = {
  G: LORD,
  palette: humanPalette({ skin: '#6a6152', cloth: '#8e2230', leather: '#4a3a2e', metal: '#666b86', accent: '#c09440', eye: '#ffb24a', picks: { metal: [0, 2, 4, 6] } }),
  legs: { S: LORD_LEGS_S, E: LORD_LEGS_E },
  head: { S: WLD_HEAD_S, E: WLD_HEAD_E, N: WLD_HEAD_N }, headX: { S: 18, E: 18, N: 18 }, headY: 2,
  torso: { S: WLD_TORSO_S, E: WLD_TORSO_E, N: WLD_TORSO_S }, torsoX: { S: 15, E: 15, N: 15 }, torsoY: 26,
  back: { S: WLD_CAPE_S, E: WLD_CAPE_S, N: null }, backAt: { S: [0, 0], E: [-3, 0], N: [0, 0] },
  // plate on plate: edged in the bottom of its own ramp, never in house ink — a black-and-lilac
  // outline ring laid down the middle of a breastplate reads as a crack, not as an arm
  limb: { lit: 'b', dark: 'a', fist: 'b', fistLit: 'c', edge: 'a' },
  style: 'swing',
  // the greatsword rises across him and PAST the pauldron, three pixels clear of the helm
  rest: { S: { gx: 27, gy: 44, a: 32, len: 32 }, E: { gx: 43, gy: 43, a: 38, len: 32 }, N: { gx: 42, gy: 44, a: 28, len: 32 } },
  offRest: { S: { gx: 31, gy: 47 }, E: { gx: 37, gy: 47 }, N: { gx: 35, gy: 47 } },
  weapon: (f, o) => bladePix(LORD, o.gx, o.gy, o.angle, { len: o.len, w0: 2.0, w1: 1.4, glint: o.glint || 0, guard: 5, grip: '8', pommel: 'g', fuller: true }),
  // the cape from behind is drawn OVER the body: at the north facing it is the whole silhouette
  idleExtra: (f, phase, dy) => (f === 'N' ? [L(WLD_CAPE_N, 0, dy)] : []),
};

// ------------------------------------------------------------------------------------ registry
const cache = new Map();
const build = (key, spec) => () => {
  let b = cache.get(key);
  if (!b) { b = buildSpecies(spec); cache.set(key, b); }
  return b;
};

/**
 * The six trained-fighter sprite builders, keyed by MONSTER_TABLE type. Every key here is a type
 * the game can actually spawn — nothing in this file draws a monster that does not exist.
 * @type {Object<string, () => object>}
 */
export const HUMAN_BUILDERS = {
  'dwarven-guard': build('dwarven-guard', DWARVEN_GUARD),
  'mercenary': build('mercenary', MERCENARY),
  'swordsman': build('swordsman', SWORDSMAN),
  'monk': build('monk', MONK),
  'dark-warrior': build('dark-warrior', DARK_WARRIOR),
  'war-lord': build('war-lord', WAR_LORD),
};

export { buildSpecies, bladePix, beardAxePix, staffPix, bucklerPix, capePix, limbPix, LEGS_S, LEGS_E };
