// atlas2d: the owner's sprite-sheet atlas, and one texture per sprite.
//
// Its own module because BOTH `props.js` (the loot pickups) and `props/props2d.js` (the decor) draw
// from it, and props2d.js already borrows the billboard builder from props.js — putting the atlas in
// either of them makes an import cycle.
//
// The atlas and its map are generated by `tools/props2d-import/` (slice, then pack); a sprite's rect is
// in the atlas's own pixels, at the art's NATIVE resolution — the packer detects art handed over at 2x
// or 16x and resamples it back down, so `w`/`h` here are real art pixels and can be read as texels.
import * as THREE from 'three';
import { PROPS2D, PROPS2D_ATLAS } from '../../assets/props2d/map.js';

/**
 * A LOWER ROW DRAWS OVER A HIGHER ROW (owner, 2026-09-21: "for 2d assets, assets on a lower row should draw
 * over assets on a higher row"). Every upright 2D piece — the cast, a sheet prop, a pickup — is a card lying
 * flat on the floor, and a tall one reaches north over the row above it. All of them sat at one height, so
 * where two overlapped the depth test was a coin toss. Now each is raised `ROW_LIFT` per row it stands on
 * (south = down the screen = higher), on a common base `STAND_Y`, so the one nearer the bottom of the screen
 * is nearer the camera and wins: painter's order, from the depth buffer. 0.002 a row is 0.16 at row 80 —
 * invisible under a camera 20 units up — and still eight depth-buffer steps at that distance. The cast
 * takes a hair more (`CAST_EDGE`) so it stands in front of a prop on its own row.
 * FLAT art — a pit, stairs, a rug, a pool — is NOT lifted: it is the floor, and stays under everything.
 */
export const ROW_LIFT = 0.002;
export const STAND_Y = 0.05;
export const CAST_EDGE = 0.0005;
export const rowLift = (z) => ROW_LIFT * z;
const FLAT_NAMES = new Set(['pit', 'stairs-down', 'stairs-up', 'lava-pool', 'rugs-strip', 'magic-circle', 'trap-rune',
  'teleporter', 'bridge', 'broken-bridge', 'spike-trap']);
/** Is this sheet sprite floor art (drawn under everything) rather than an upright piece? */
export function isFlatSprite(name) {
  return !!name && (FLAT_NAMES.has(name) || /^(floor-(pit|stairs|spikes)|pool-|trapdoor-)/.test(name));   // not floor-torch: it stands
}

const URL_ATLAS = new URL('../../assets/props2d/atlas.png', import.meta.url).href;
let atlas = null;
const texCache = new Map();

/** The shared atlas texture, loaded once. Nothing waits for it: a sprite appears when it lands. */
export function atlasTexture() {
  if (atlas) return atlas;
  atlas = new THREE.TextureLoader().load(URL_ATLAS);
  atlas.colorSpace = THREE.SRGBColorSpace;
  atlas.magFilter = THREE.NearestFilter;
  atlas.minFilter = THREE.NearestFilter;
  atlas.generateMipmaps = false;
  return atlas;
}

/** One sprite of the atlas as its own texture (a clone sharing the image, with its own window). */
export function spriteTexture(name) {
  if (texCache.has(name)) return texCache.get(name);
  const r = PROPS2D[name];
  if (!r) return null;
  const t = atlasTexture().clone();
  t.needsUpdate = true;
  t.repeat.set(r.w / PROPS2D_ATLAS.w, r.h / PROPS2D_ATLAS.h);
  t.offset.set(r.x / PROPS2D_ATLAS.w, 1 - (r.y + r.h) / PROPS2D_ATLAS.h);
  texCache.set(name, t);
  return t;
}

/** The sprite's rect, or null. */
export function spriteRect(name) { return PROPS2D[name] || null; }

/**
 * The size in TEXELS for a sprite asked to stand `tiles` wide. The sheet's art is not drawn at this
 * game's 32-texels-a-tile, so every caller states the width it wants in tiles and the height follows
 * the art's own proportions.
 */
export function spriteTexels(name, tiles, texelsPerTile = 32) {
  const r = PROPS2D[name];
  if (!r) return null;
  const w = tiles * texelsPerTile;
  return { w, h: w * (r.h / r.w) };
}

/** How hard the room lights a sprite lying on the floor (see props2d.js SHEET_TUNE). */
const GROUND_ALBEDO = 0.62;

/**
 * THE OTHER WAY TO PUT A SPRITE IN THE WORLD: flat on the floor, as a piece of the board rather than a
 * standee (owner, 2026-09-20: "attach it as a texture to a 3d-square, and position that square on the
 * ground in the same coordinates you would for any prop").
 *
 * It is a plain quad in the FLOOR PLANE at the tile's own coordinates, `tiles` wide, sized from the art's
 * proportions. Nothing billboards, nothing snaps, nothing is sized from the camera: it is geometry in the
 * world like the flagstones under it, so it holds still exactly as well as they do and turns with the
 * camera because it is lying there. Straight down it reads face-on; at a tilt it foreshortens like a card
 * on a table, which is the honest trade.
 * @param {string} name a sprite in the sheet atlas
 * @param {{tiles?:number, y?:number, facing?:string}} [o]
 */
export function buildGroundSprite(name, o = {}) {
  const rect = spriteRect(name), tex = spriteTexture(name);
  if (!rect || !tex) return null;
  const w = o.tiles ?? 0.9, h = w * (rect.h / rect.w);
  const g = new THREE.Group();
  const geo = new THREE.PlaneGeometry(w, h).rotateX(-Math.PI / 2);
  const mat = new THREE.MeshStandardMaterial({
    map: tex, transparent: false, alphaTest: 0.5, roughness: 1, metalness: 0,
    emissiveMap: tex, emissive: new THREE.Color(0xffffff), emissiveIntensity: 0.12,
    color: new THREE.Color(GROUND_ALBEDO, GROUND_ALBEDO, GROUND_ALBEDO),
  });
  const m = new THREE.Mesh(geo, mat);
  m.position.y = o.y ?? 0.02;                    // a hair off the flagstone, like a floor decal
  m.rotation.y = { n: Math.PI, e: -Math.PI / 2, s: 0, w: Math.PI / 2 }[o.facing || 's'] || 0;
  m.receiveShadow = false; m.castShadow = false;
  g.add(m);
  g.userData.decor = { type: name, variant: 0, facing: o.facing || 's', cls: 'decal', sheet: name, ground: true };
  return g;
}

