// Fold src/assets/supplied/*.glb and *.webp into one generated module, src/assets/supplied/data.js.
//
//   node tools/supplied-import/pack.mjs
//
// The single-file build (tools/bundle.mjs) allows neither fetch() nor data: URIs, so — exactly like
// the Freeport library beside it (tools/freeport-import/pack.mjs) and the Dungeon Crawlers library
// before that (src/assets/propsModel.js) — the bytes ship inside the JS bundle as base64 and are
// decoded on first use. No gzip: the textures are already WebP, and a synchronous parse of the
// geometry is what lets a room build its furniture in the same frame.
//
// Unlike Freeport's packer this one keys by ASSET, not by file name, and carries the numbers the
// importer measured beside the bytes, so the runtime never has to re-derive a footprint or guess
// which meshes a glb holds:
//
//   SUPPLIED_FILES[id] = {
//     glb, tex, texSmall,     base64; texSmall is the half-size copy for phones
//     parts,                  mesh names inside the glb, in the order the importer wrote them
//     sizeTiles: [x, y, z],   bounding box in tiles, standing on y = 0 and centred on x/z
//     uvPerTile,              chart uv per world unit; times texSize.desk gives texels per tile
//     texSize: {desk, small}, the two WebP sizes in pixels (square)
//     triangles,
//     source: { pack, prefab },
//     cutout,                 true only where the baked chart really carries translucent texels
//   }
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const DIR = path.join(REPO, 'src/assets/supplied');
const rows = JSON.parse(fs.readFileSync(path.join(DIR, 'supplied.json'), 'utf8'));
const b64 = (f) => { const b = fs.readFileSync(path.join(DIR, f)); return { s: b.toString('base64'), n: b.length }; };

let js = '// GENERATED by tools/supplied-import/pack.mjs from the .glb and .webp files beside it. Do not edit.\n';
js += '// See README.md in this folder for the sources, the settings and the per-asset numbers.\n';
js += '/** asset id -> base64 bytes + the numbers the importer measured */\nexport const SUPPLIED_FILES = {\n';
let total = 0, glbTotal = 0, texTotal = 0;
for (const r of rows) {
  const glb = b64(`${r.id}.glb`), tex = b64(`${r.id}.webp`), small = b64(`${r.id}_small.webp`);
  total += glb.n + tex.n + small.n; glbTotal += glb.n; texTotal += tex.n + small.n;
  js += `  ${r.id}: {\n`;
  js += `    parts: ${JSON.stringify(r.parts)}, sizeTiles: ${JSON.stringify(r.sizeTiles)}, uvPerTile: ${r.uvPerTile},\n`;
  js += `    triangles: ${r.triangles}, cutout: ${!!r.cutout}, texSize: ${JSON.stringify(r.tex)},\n`;
  js += `    source: ${JSON.stringify(r.source)},\n`;
  if (r.anchors) js += `    anchors: ${JSON.stringify(r.anchors)},\n`;
  js += `    glb: '${glb.s}',\n    tex: '${tex.s}',\n    texSmall: '${small.s}',\n  },\n`;
  console.log(`${r.id.padEnd(20)} glb ${(glb.n / 1024).toFixed(1).padStart(6)} KB  tex ${(tex.n / 1024).toFixed(1).padStart(5)} KB + ${(small.n / 1024).toFixed(1).padStart(5)} KB`);
}
js += '};\n\n';
const d = new Date(); const day = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
js += `export const SUPPLIED_META = { version: 1, built: '${day}', importer: 'tools/supplied-import', assets: ${rows.length} };\n`;
fs.writeFileSync(path.join(DIR, 'data.js'), js);
console.log(`\n${rows.length} assets: ${(glbTotal / 1024).toFixed(1)} KB glb + ${(texTotal / 1024).toFixed(1)} KB webp = ${(total / 1024).toFixed(1)} KB raw -> data.js ${(js.length / 1024).toFixed(1)} KB`);
