// Slice a hand-painted tile sheet into the game's floor-atlas cells.
//
// Usage: node tools/tilesheet-import.mjs "<sheet.png>" [--rows 6] [--out src/assets/tilesheet.js]
//
// THE ONE RULE THIS TOOL EXISTS TO ENFORCE (CLAUDE.md rule 2: one pixel grid)
// The source sheet is painted at ~96px a tile. The game is drawn at TEXELS_PER_TILE = 32 texels a
// world tile, and the cast and the props are on that grid. Sampling these tiles at their native
// density would put the floor at three times the resolution of everything standing on it, which is
// the exact "two resolutions on one screen" failure this project keeps coming back to. So every
// cell is box-filtered down to 32x32 here, ONCE, at import — not stretched at runtime.
//
// The grid is DETECTED, not assumed: the sheet's cells are separated by black gutters, so a column
// (or row) of the image that is almost entirely black is a gutter, and the cells are the runs
// between them. That survives a re-export at a different size or with different padding.
import { launchBrowser } from './browser.mjs';
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';

const argv = process.argv.slice(2);
const src = argv.find((a) => !a.startsWith('--'));
const arg = (k, d) => { const i = argv.indexOf('--' + k); return i < 0 ? d : argv[i + 1]; };
if (!src) { console.error('usage: node tools/tilesheet-import.mjs "<sheet.png>" [--rows N] [--out path]'); process.exit(2); }
const KEEP_ROWS = Number(arg('rows', 6));      // the top N rows; the bottom rows are objects, not fields
const CELL = Number(arg('cell', 32));          // = TEXELS_PER_TILE
const out = arg('out', 'src/assets/tilesheet.js');

const b64src = fs.readFileSync(src).toString('base64');
const b = await launchBrowser({ width: 400, height: 300 });
let code = 0;
try {
  const r = await b.page.evaluate(async ({ b64src, KEEP_ROWS, CELL }) => {
    const img = new Image();
    await new Promise((res, rej) => { img.onload = res; img.onerror = () => rej(new Error('decode failed')); img.src = 'data:image/png;base64,' + b64src; });
    const c = document.createElement('canvas'); c.width = img.width; c.height = img.height;
    const cx = c.getContext('2d', { willReadFrequently: true });
    cx.drawImage(img, 0, 0);
    const d = cx.getImageData(0, 0, c.width, c.height).data;
    const dark = (i) => (d[i] + d[i + 1] + d[i + 2]) / 3 < 28;

    // gutters: a line that is >=72% black. The runs BETWEEN them are the cells.
    const gutters = (n, m, at) => {
      const frac = [];
      for (let i = 0; i < n; i++) { let k = 0; for (let j = 0; j < m; j++) if (dark(at(i, j))) k++; frac.push(k / m); }
      const runs = []; let s = -1;
      frac.forEach((v, i) => { if (v >= 0.72) { if (s < 0) s = i; } else { if (s >= 0) runs.push([s, i - 1]); s = -1; } });
      if (s >= 0) runs.push([s, frac.length - 1]);
      return runs;
    };
    const spans = (runs) => runs.slice(0, -1).map((g, i) => [g[1] + 1, runs[i + 1][0] - 1]).filter(([a, z]) => z - a > 8);
    const colSpans = spans(gutters(c.width, c.height, (x, y) => (y * c.width + x) * 4));
    const rowSpans = spans(gutters(c.height, c.width, (y, x) => (y * c.width + x) * 4));
    const rows = Math.min(KEEP_ROWS, rowSpans.length), cols = colSpans.length;

    // Pack the kept cells into one atlas, each box-filtered down to CELL x CELL. drawImage with
    // smoothing on is an area average when the target is an integer fraction of the source, which
    // is what a ~96 -> 32 downsample wants; nothing here is nearest-sampled.
    const a = document.createElement('canvas'); a.width = cols * CELL; a.height = rows * CELL;
    const ax = a.getContext('2d', { willReadFrequently: true });
    ax.imageSmoothingEnabled = true; ax.imageSmoothingQuality = 'high';
    for (let ry = 0; ry < rows; ry++) for (let rx = 0; rx < cols; rx++) {
      const [x0, x1] = colSpans[rx], [y0, y1] = rowSpans[ry];
      ax.drawImage(img, x0, y0, x1 - x0 + 1, y1 - y0 + 1, rx * CELL, ry * CELL, CELL, CELL);
    }
    const px = ax.getImageData(0, 0, a.width, a.height).data;
    return { w: a.width, h: a.height, cols, rows, cell: CELL, srcW: c.width, srcH: c.height, bytes: Array.from(px) };
  }, { b64src, KEEP_ROWS, CELL });

  const gz = zlib.gzipSync(Buffer.from(Uint8Array.from(r.bytes)), { level: 9 });
  const body = `// GENERATED by tools/tilesheet-import.mjs - do not edit by hand.
// A hand-painted tile sheet, sliced to the game's own grid: every cell box-filtered down to
// ${r.cell}x${r.cell} texels (= TEXELS_PER_TILE) at import, so the floor cannot end up at a finer
// resolution than the cast standing on it. Source sheet ${r.srcW}x${r.srcH}, top ${r.rows} rows kept.
// Cell (col, row) is 0-based from the top-left; the sheet's own printed labels are 1-based.
export const SHEET_COLS = ${r.cols}, SHEET_ROWS = ${r.rows}, SHEET_CELL = ${r.cell};
export const SHEET_W = ${r.w}, SHEET_H = ${r.h};
export const SHEET_RGBA_GZ_B64 = '${gz.toString('base64')}';
`;
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, body);
  console.log(`${r.cols} x ${r.rows} cells from ${r.srcW}x${r.srcH} -> ${r.w}x${r.h} atlas, ${(gz.length / 1024).toFixed(0)} KB gzipped -> ${out}`);
  if (b.errors.length) { console.error('PAGE ERRORS:\n' + b.errors.join('\n')); code = 1; }
} catch (e) { console.error(e); code = 1; }
finally { await b.close(); }
process.exit(code);
